#+title: April

* Sripetch v SEC // https://www.scotusblog.com/cases/case-files/sripetch-v-securities-and-exchange-commission/
- Levine writes about the difficulty in matching the profiteers to victims. // https://archive.ph/xnWAO
- Sripetch bought penny stocks and then promoted them through intermediaries and match traded them to inflate trade volumes. Sripetch was prosecuted and pleaded guilty to sale of unregistered securities. The SEC brough civil-eforcement suit against Sripetch for securities fraud and selling unregistered securities. Sripetch consented to an injunction of future violations and a bar on paticipating in offerings of penny stock. Sripetch did not consent to disgorgement. The SEC is seeking $2.2 million in dosgorgement plus interest. The district court found in favor of SEC. The 9th circuit affirmed on different grounds. Now Sripetch appeals to SCOTUS.
- 78u(d)(3): "Whenever it shall appear to the Commission that any person has violated any provision of this chapter [...] [a] court shall have jurisdiction to (ii) require disgorgement under paragraph (7) of any unjust enrichment by the person who received such unjust enrichment as a result of such violation."
- Sripetch argues that disgorgement is an equitable remedy. Disgorgement restores the status quo by taking the ill-gotten gains from the wrong-doer and returning what was lost to the victims. The victims here have lost nothing (there is no "pecuniary harm") so disgorgement is inappropriate. Disgorgement can't be used as a penalty because it's purpose is compesatory, not punitive. The SEC has other options for seeking penalties; the SEC's theory of disgorgement evades congress's processes and limitations for them.
- The SEC argues that disgorgement does not require proof of pecuniary harm. Disgorgement is based on equity and "it would be quintessentially inequitable to permit a known wrongdoer to profit from his own misdeeds." The text of 78u(d) does not include a pecuniary harm. Other provisions condition remedies on economic loss, the disgorgement provision does not.
- After Liu v SEC congress passed an explicit disgorgement provision (parts of 78u(d)). Sripetch argues that those provisions to codify Liu. The SEC argues that the provisions support their interpretation.
- I should really read Liu before making a prediction. Liu "limited disgorgement to the wrongdoer's net profits and must be awarded for victims" (wikipedia).  After Liu congress passed a law that didn't say anything about the victims. The text of the law seems to clearly empower the court to "require disgorgement [...] of any unjust enrichment" and you don't need pecuniary harm to have been unjustly enriched. SEC wins.

* TM v University of Maryland Medical System Corp. // https://www.scotusblog.com/cases/case-files/t-m-v-university-of-maryland-medical-system-corp/
- TM has a psichiatric condition which she and her private physician attribute to gluten sensitivity. TM signed an advancd directive stating: if she becomes psychotic her Father will become her health-care agent. In 2023 TM had a psychotic episode and was brought to Baltimore Washington Medical Center (BWMC) by police. The hospital staff determined that TM's advance directive was invalid, diagnosed her with schizophrenia and, following a hearing with an ALJ, had her involuntarily admitted over her and her family's objections. The hospital began proceedings to have her injected with a longer lasting form of her antipsychotic medication. TM went to state court to be released from the hospital. TM was able to negotiate a settlement agreement. Under this consent order TM would be released  but must find a new psychiatrist, take her medication, and dismiss her many lawsuits. After being released TM dismissed her other lawsuits but brought another, now challenging the consent order. TM brough an additional lawsuit in Federal court, successfully staying the state court proceedings in the meantime. The district court found, under Rooker-Feldman, that it lacked jurisdiction to challenge the proceedings below at this time. The fourth circuit affirmed and now TM is appealing to SCOTUS.
- TM argues that Rooker-Feldman only applies where statute precludes a district court from reviewing a state-court judgement. Rooker-Feldman comes from 28 USC 1257 which only talks about jurisdiction over appeals from "[f]inal judgments or decrees rendered by the highest court of a State in which a decision could be had" which this is not. Rooker-Feldman is confusing and bad and should be retired.
- UMMS argues that district courts lack jurisdiction to review state court judgements because they were not granted jurisdiction by congress. State court decisions must be appealed through state appellate courts. Once the highest state court has ruled then SCOTUS has jurisdiction to hear appeals. (I don't understand how their argument relies on Rooker-Feldman at all.)
- The facts here seem goofy. What's going on with this lady's psychiatrist? Why was she held involuntarily for so long? But none of this matters here.

* FCC v AT&T
- Cell providers sell customer location data to location aggregators who in turn sell that data to service providers. FCC rules require the cell providers to review the service provider's use case and user consent to avoid misuse. In 2018 news revealed misuse of customer data by service providers. The FCC determined that AT&T violated its rules and levied a $50m forfeiture order. Similar determinations and forfeiture orders were made toward Verizon (copetitioner), Sprint, and T-Mobile. All cell providers paid the fines but went to federal court arguing that the FCC's in-house procedure violates the 7th amendment right to a jury trial. The 2nd and DC circuits found no 7th amendment violation. AT&T appealed to the 5th circuit which found that it did, and AT&T had a right to a jury trial.
- 7a: "In Suits at common law, where the value in controversy shall exceed twenty dollars, the right of trial by jury shall be preserved[.]"
- AT&T argues that monetary forfeiture penalties are common-law remedies so the 7th amendment requires access to a jury trial. This is a negligence case, which is also common-law. Waiting for the DOJ to bring a collection suit does not satisfy the 7th amendment. Defendants must have access to a jury before the FCC enters a forfeiture order. The collections suit is a separate suit, granting a separate right to a jury trial. Waiting for a collections suit leaves the defendant with reputational harm while they defy the FCC, as well other punishments within the FCC's discretion. The Defendant can't appeal (as they are here) until it pays the penalty, so if the defendant wants to defy the penalty it must give up their right to appeal.
- The FCC argues that defendants are not obligated to pay foreiture orders until the DOJ brings a collection suit, so there is no jury tiral right until the collection suit. The FCC's adjudication "is not a suit, is not a proceeding at common law, and is not for more than $20." Forfeiture is really important, and the FCC will be able to do less of it if it requires a jury trial!
  
* Blanche v Lau
- Lau moved to the United States in 2007 and became a lawful permanent resident. In 2012 Lau sould $282,000 worth of counterfit apparel. Lau left the country and returned while awaiting trial. When returnning Lau was stopped by immigration officers and paroled into the United States for deferred inspection. In 2013 Lau pleaded guilty to counterfiting. In March 2014 DHS began removal proceedings because Lau was inadmissible when paroled in 2012. An immigration judge ordered him removed to China and the Board of Immigration Appeals affirmed. Lau appealed to the 2nd Circuit found that the 2012 parole was improper and vacated the removal order. Now DHS appeals to SCOTUS.
- 1101(a): "[An LPR] shall not be regarded as seeking an admission into the United States [...] unless the alien [...] has committed an offense identified in section 1182(a)(2) of this title"
- 1182(a)(2)(A)(i): "a crime involving moral turpitude"
- DHS argues that 2nd erred in finding that Lau was improperly paroled and therefore admitted. The INA says "no court shall have jurisdiction to review" a discretionary parole decision. The 2nd circuit's rule limits the government to information available to the 2012 immigration officers, but the INA decision should be based on the evidence produced at the immigration hearing which occured after Lau's conviction. The 2nd circuits rule would require mini-trials with clear and convicing evidence by immigration officers at ports of entry, this is dumb and can't be what congress legislated.
- Lau argues that the 2nd court was correct. Lau could not be properly paroled because the government couldn't show he had committed "a crime involving moral turpitude" with "clear and convicing evidence". That "clear and convicing evidence" standard must be met at the time of entry. The courts may not review proper excercies of discretion but man review any question of law. The government's rule would allow them to stretch the period of "arriving" arbitrarily, and justify the parole if and when it finds a justification. DHS's "mini-trials" is a policy argument without textual support. If DHS wants to remove LPRs it must go through deportation under 1227.
- Lau argues that DHS is using 1182's returning LPR exceptions to evade the procedural requirements of 1227 removal. I find this argument convicing. The government should be going through ordinary deporation proceedings for LPRs. Lau wins.

* Chatrie v United States // https://www.scotusblog.com/cases/chatrie-v-united-states/
- Chatrie is being prosecuted for robbing a Federal Credit Union in May 2019. During the investigation the police noted that the suspect used a cell phone and applied for and received a geofence warrant to search Google's location history. Google has a 3-step process for responding to such geofence warrants. At step 1 Google provided anonymized data for 19 users who were in the geofence from 4:20-5:20pm. At step 2 the detective requested additional data for 9 users and Google provided all location data for those users from 3:50-5:50pm. At step 3 the detective requested deanonymized data for 3 users which Google provided. (At step 2 the detective initially requested additional data for all 19 users but Google refused. The detective never gave reasons for his choice of users.) Chatrie was one of the 3 deanonymized users. Chatrie challenged the geofence warrant, arguing that it violated the 4th amendment. The district court (E.D.Va.) agreed that the warrant violated the 4th amendment but declined to suppress its evidence under the good-faith exception to the exclusionary rule. Chatrie appealed to the 4th circuit which affirmed. The 4th circuit reheard the case en banc and affirmed based on splintered reasoning. Chatrie now appeals to SCOTUS.
- 4a: "The right of the people to be secure in their persons, houses, papers, and effects, against unreasonable searches and seizures, shall not be violated, and no Warrants shall issue, but upon probable cause, supported by Oath or affirmation, and particularly describing the place to be searched, and the persons or things to be seized."
- good-faith exception: ["Under the good-faith exception, evidence is not excluded if it is obtained by officers who reasonably rely on a search warrant that turns out to be invalid."](https://www.law.cornell.edu/wex/exclusionary_rule)
- Chatrie argues that: searching Google's location history is a 4th amendment search, the geofence warrant was unconstitutional, and the step 2 and 3 searches were separately unconstitutional.
  Location history is a user's data stored in the user's Google account. Users have a property interest and a reasonable expectation of privacy in their location history. Google holds the user's data as a bailee, it is not Google's business records which would be Google's to give over.
  The geofence warrant was a search of millions of people's location history. The warrant's search of "Google" in "insufficiently particularized." Just as a warrant would have to specify an appartment or package as opposed to a building or neighborhood, a warrant seeking location history must identify a particular user account. Even if the search was only of the 19 users from step 1 those users being in a certain place at a certain time does not satify the 4th amendment's particularity requirement.
  At steps 2 and 3 the police conducted additional searches without providing justification. Google's review doesn't count because Google is not a judge.
- The Government argues that the 3 step process was approved by a magistrate and consistent with the 4th amendment.
  Users do not have a property interest or reasonable expectation of privacy in their location history. Chatrie assumed the risk of sharing his location history with Google. Asking Google for location data is like asking a bystandard for similar information. The geofence and time range keep the information from revealing sensitive "privacies of life". Also this argument wasn't made below!
  The police had probable cause to believe that Google had location information on the robber, his accomplices, or potential witnesses, because they saw him using a phone. That warrant was only for necessary information and was narrowed at each of the 3 steps to protect privacy. The warrant did not allow, and the police did not conduct, a search of millions of users. 
  Petitioner's test would make all geofence warrants unconstitutional!
  
* Monsanto Company v Durnell // https://www.scotusblog.com/cases/monsanto-company-v-durnell/
- John L. Durnell was diagnosed with non-Hodgkin lymphoma in 2018. He blames his use of Monsanto's Roundup and sued them in Missouri state court. A jury found that Roundup caused Durnell's Cancer and that Roundup "lacked an adequate warning". The jury awarded Durnell $1.25m for "failure-to-warn". Monsanto appealed to the Missouri Court of Appeals arguing that such state law claims are preempted by the Federal Insecticide, Fungicide, and Rodenticide Act (FIFRA). The Missouri Court of Appeals affirmed the decision below and the Missouri Supreme Court declined to hear the case. Monsanto now appeals to SCOTUS.
- 7 usc 136v(b):  "[A] State shall not impose or continue in effect any requirements for labeling or packaging in addition to or different from those required under this subchapter."
- 7 usc 136a(f)(2): "In no event shall registration of an article be construed as a defense for the commission of any offense under this subchapter. [...] registration of a pesticide shall be prima facie evidence that the pesticide, its labeling and packaging comply with the registration provisions of the subchapter."
- Monsanto argues that FIFRA's labeling requirements preempt this State law "failure-to-warn" claim. FIFRA requires pesticide makers to distribute their products with labeling not "substantially different from the EPA-approved label." The EPA has found that Roundup does not cause cancer and has approved labels reflecting that. Durnell claims that Roundup does cause cancer and must warn cunsumers on its label. This claim imposes "requirements for labeling [...] in addition to or different from those required under [FIFRA]" violating 136v(b). Here complying with both requirements is impossible, such a label would violate FIFRA. EPA has approved a label without a cancer warning so Monsanto is not free to change it without EPA's further approval. EPA will not approve such a label because it would be false or misleading. If Monsanto could add a cancer warning to the label EPA would consider that warning "false or misleading" in violation of FIFRA. Congress' purpose in passing FIFRA was to create uniformity and avoid exactly these contradictory ends.
- Durnell argues that EPA-approval only means that the pesticide comports with registration requirements. EPA's approval does not mean that the label comports with FIFRA's misbranding provision or state law failure-to-warn requirements, and the EPA could not make such a finding. "Under Loper Bright, it is for courts to determine the meaning of FIFRA’s provisions [...]". This is exactly what 136a(f)(2) is talking about.
  Monsanto can add a cancer warning without EPA's approval. Monsanto can add an indisputably truthful warning to avoid being mislabeled under FIFRA. (The brief gives the examle: “The International Agency for Research on Cancer considers glyphosate probably carcinogenic to humans.”) And if Monsanto cannot sell Roundup while following State and Federal law they don't get to ignore State law, they simply can't sell Roundup.
  
* Cisco Systems, Inc. v Doe I // https://www.scotusblog.com/cases/cisco-systems-inc-v-doe-i/
- China has long used technolgy to track Falun Gong believers, a religious minority in China. The system China created to do this is called Golden Shield. China has used Golden Shield to persecute Falun Gong believers, subjecting them to surveilance, arbitrary detention, forced conversions, sham trials, torture, and death. Plaintiffs alledge that Cisco created custom products and training for Golden Shield. They brought suit in district court against Cisco and two former executives, accusing them of aiding and abetting China's violation of the Torture Victim Protection Act. The district court dismissed the claims, finding that aiding-and-abetting was not actionable under the TVPA. The 9th circuit reversed finding that the TVPA did authorize aiding-and-abetting suits and that plaintiff's complaint could proceed. The 9th circuit denied rehearing en banc over the a dissent representing 6 members. Now Cisco appeals to SCOTUS.
- Cisco argues that the Alient Tort Statute does not support aiding-and-abetting claims. The ATS and TVPA do not mention aiding-and-abetting and so do not provide for aiding-and-abetting liability. The creation of a cause of action must be done by congress. Any judicial expansion to cover aiding-and-abetting claims would be especially inappropriate. Aiding-and-abetting liability would dramatically expand liability under a statute that has been correctly read with "great caution". Aiding-and-abetting litigation under ATS would involve the courts making findings of the actions of foreign sovereigns. (Here the Chinese officials accused of torture, etc.) Even if aiding-and-abetting liability was available the TVPA allows for claims only against those perform the torture and those who direct it, not those who aid-and-abet.
- Plaintiffs argue that the ATS would have recognized aiding-and-abetting as understood at the founding so federal courts may recognize them today. The ATS has historically provided causes of action for violations of safe conducts, piracy, and assaults on ambassadors. Congress would not have left an assaulted ambassador unable to seek redress against those who facilitated their assault. Such aiding-and-abetting liability also would not interfere with foreign relations. This case does not interfere with foreign relations because, as a matter of policy, the US seeks to deter complicity with China's persecution of religious minorities. The first congress intended for the courts to enforce the law of nations through the ATS by recognizing causes of action. The TVPA provides liability for those who "subject another to torture" and Cisco was "subjecting" plaintiffs to torture by aiding-and-abetting.(?)
  
* Mullin v Doe // https://www.scotusblog.com/cases/noem-v-doe-3/
- In 2012 the Obama administration designated Syria for Temporary Protected Status (TPS) under 8 usc 1254a. DHS Secretary Napolitano justified this based on Assad's crackdown on protestors, civilians, and media. And later based on an ongoing armed conflict. TPS status was extended until September 22, 2025 when the Trump administration announced it termination in 60 days. Then DHS secretary Noem cited the fall of the Assad regime, reduction in violence, and improvements under Syria's interim president. Noem argued that supporting TPS for Syria riked public safety and national security. Noem cited foreign policy goals to engage with the new Syrian government and return Syrian nationals. Does (Seven Syrian nationals with TPS or pending TPS applications) brought APA and 5th amendment equal-protection challenges against Noem's termination of TPS. The district court sided with plaintiffs in enjoined the termination order. The government appealed to the 2nd circuit which denied it's requested stay. 
- consolidated with Trump v Miot // https://www.scotusblog.com/cases/trump-v-miot/
- In 2010 the Obama administration designated Haiti for TPS. The capital of Haiti had just suffered an earthquake which collapsed homes and damaged infrastructure. Hospitals and civil services were damaged or overtaxed. In 2018 the Trump administration moved to terminate the designation. A district court enjoined. The 9th circuit reversed but gratned review en banc. In 2021 the Biden administration redesignated Haiti for TPS based on "deteriorating political crisis, violence, and a staggering increase in human rights abuses." In November 2025 then-secretary Noem announced termination of Haiti's TPS. Noem cited improving conditions in Haiti as well as domestic concerns with the program. 5 Hatian TPS holders (including Miot) brought a class action complaint challenging the termination. The district court found that did not adequately consult appropriate agincies, was arbitrary and capricious under APA, and was motivated by racial animus in violation of equal-protection. The district court enjoined the termination. The government appealed to the DC Circuit for a stay, which it denied.
  
* Hikma Pharmaceuticals USA Inc. v Amarin Pharma, Inc. // https://www.scotusblog.com/cases/hikma-pharmaceuticals-usa-inc-v-amarin-pharma-inc/ 
