#+title: April

* Sripetch v SEC // https://www.scotusblog.com/cases/case-files/sripetch-v-securities-and-exchange-commission/
- Levine writes about the difficulty in matching the profiteers to victims. // https://archive.ph/xnWAO
- Sripetch bought penny stocks and then promoted them through intermediaries and match traded them to inflate trade volumes. Sripetch was prosecuted and pleaded guilty to sale of unregistered securities. The SEC brough civil-eforcement suit against Sripetch for securities fraud and selling unregistered securities. Sripetch consented to an injunction of future violations and a bar on paticipating in offerings of penny stock. Sripetch did not consent to disgorgement. The SEC is seeking $2.2 million in dosgorgement plus interest. The district court found in favor of SEC. The 9th circuit affirmed on different grounds. Now Sripetch appeals to SCOTUS.
- 78u(d)(3): "Whenever it shall appear to the Commission that any person has violated any provision of this chapter [...] [a] court shall have jurisdiction to (ii) require disgorgement under paragraph (7) of any unjust enrichment by the person who received such unjust enrichment as a result of such violation."
- Sripetch argues that disgorgement is an equitable remedy. Disgorgement restores the status quo by taking the ill-gotten gains from the wrong-doer and returning what was lost to the victims. The victims here have lost nothing (there is no "pecuniary harm") so disgorgement is inappropriate. Disgorgement can't be used as a penalty because it's purpose is compesatory, not punitive. The SEC has other options for seeking penalties; the SEC's theory of disgorgement evades congress's processes and limitations for them.
- The SEC argues that disgorgement does not require proof of pecuniary harm. Disgorgement is based on equity and "it would be quintessentially inequitable to permit a known wrongdoer to profit from his own misdeeds." The text of 78u(d) does not include a pecuniary harm. Other provisions condition remedies on economic loss, the disgorgement provision does not.
- After Liu v SEC congress passed an explicit disgorgement provision (parts of 78u(d)). Sripetch argues that those provisions to codify Liu. The SEC argues that the provisions support their interpretation.
- I should really read Liu before making a prediction. Liu "limited disgorgement to the wrongdoer's net profits and must be awarded for victims" (wikipedia).  After Liu congress passed a law that didn't say anything about the victims. The text of the law seems to clearly empower the court to "require disgorgement [...] of any unjust enrichment" and you don't need pecuniary harm to have been unjustly enriched. SEC wins.

* TM v University of Maryland Medical System Corp. // https://www.scotusblog.com/cases/case-files/t-m-v-university-of-maryland-medical-system-corp/
- TM has a psichiatric condition which she and her private physician attribute to gluten sensitivity. TM signed an advancd directive stating: if she becomes psychotic her Father will become her health-care agent. In 2023 TM had a psychotic episode and was brought to Baltimore Washington Medical Center (BWMC) by police. The hospital staff determined that TM's advance directive was invalid, diagnosed her with schizophrenia and, following a hearing with an ALJ, had her involuntarily admitted over her and her family's objections. The hospital began proceedings to have her injected with a longer lasting form of her antipsychotic medication. TM went to state court to be released from the hospital. TM was able to negotiate a settlement agreement. Under this consent order TM would be released  but must find a new psychiatrist, take her medication, and dismiss her many lawsuits. After being released TM dismissed her other lawsuits but brought another, now challenging the consent order. TM brough an additional lawsuit in Federal court, successfully staying the state court proceedings in the meantime. The district court found, under Rooker-Feldman, that it lacked jurisdiction to challenge the proceedings below at this time. The fourth circuit affirmed and now TM is appealing to SCOTUS.
- TM argues that Rooker-Feldman only applies where statute precludes a district court from reviewing a state-court judgement. Rooker-Feldman comes from 28 USC 1257 which only talks about jurisdiction over appeals from "[f]inal judgments or decrees rendered by the highest court of a State in which a decision could be had" which this is not. Rooker-Feldman is confusing and bad and should be retired.
- UMMS argues that district courts lack jurisdiction to review state court judgements because they were not granted jurisdiction by congress. State court decisions must be appealed through state appellate courts. Once the highest state court has ruled then SCOTUS has jurisdiction to hear appeals. (I don't understand how their argument relies on Rooker-Feldman at all.)
- The facts here seem goofy. What's going on with this lady's psychiatrist? Why was she held involuntarily for so long? But none of this matters here.

* FCC v AT&T
- Cell providers sell customer location data to location aggregators who in turn sell that data to service providers. FCC rules require the cell providers to review the service provider's use case and user consent to avoid misuse. In 2018 news revealed misuse of customer data by service providers. The FCC determined that AT&T violated its rules and levied a $50m forfeiture order. Similar determinations and forfeiture orders were made toward Verizon (copetitioner), Sprint, and T-Mobile. All cell providers paid the fines but went to federal court arguing that the FCC's in-house procedure violates the 7th amendment right to a jury trial. The 2nd and DC circuits found no 7th amendment violation. AT&T appealed to the 5th circuit which found that it did, and AT&T had a right to a jury trial.
- 7a: "In Suits at common law, where the value in controversy shall exceed twenty dollars, the right of trial by jury shall be preserved[.]"
- AT&T argues that monetary forfeiture penalties are common-law remedies so the 7th amendment requires access to a jury trial. This is a negligence case, which is also common-law. Waiting for the DOJ to bring a collection suit does not satisfy the 7th amendment. Defendants must have access to a jury before the FCC enters a forfeiture order. The collections suit is a separate suit, granting a separate right to a jury trial. Waiting for a collections suit leaves the defendant with reputational harm while they defy the FCC, as well other punishments within the FCC's discretion. The Defendant can't appeal (as they are here) until it pays the penalty, so if the defendant wants to defy the penalty it must give up their right to appeal.
- The FCC argues that defendants are not obligated to pay foreiture orders until the DOJ brings a collection suit, so there is no jury tiral right until the collection suit. The FCC's adjudication "is not a suit, is not a proceeding at common law, and is not for more than $20." Forfeiture is really important, and the FCC will be able to do less of it if it requires a jury trial!
  
* Blanche v Lau
- Lau moved to the United States in 2007 and became a lawful permanent resident. In 2012 Lau sould $282,000 worth of counterfit apparel. Lau left the country and returned while awaiting trial. When returnning Lau was stopped by immigration officers and paroled into the United States for deferred inspection. In 2013 Lau pleaded guilty to counterfiting. In March 2014 DHS began removal proceedings because Lau was inadmissible when paroled in 2012. An immigration judge ordered him removed to China and the Board of Immigration Appeals affirmed. Lau appealed to the 2nd Circuit found that the 2012 parole was improper and vacated the removal order. Now DHS appeals to SCOTUS.
- 1101(a): "[An LPR] shall not be regarded as seeking an admission into the United States [...] unless the alien [...] has committed an offense identified in section 1182(a)(2) of this title"
- 1182(a)(2)(A)(i): "a crime involving moral turpitude"
- DHS argues that 2nd erred in finding that Lau was improperly paroled and therefore admitted. The INA says "no court shall have jurisdiction to review" a discretionary parole decision. The 2nd circuit's rule limits the government to information available to the 2012 immigration officers, but the INA decision should be based on the evidence produced at the immigration hearing which occured after Lau's conviction. The 2nd circuits rule would require mini-trials with clear and convicing evidence by immigration officers at ports of entry, this is dumb and can't be what congress legislated.
- Lau argues that the 2nd court was correct. Lau could not be properly paroled because the government couldn't show he had committed "a crime involving moral turpitude" with "clear and convicing evidence". That "clear and convicing evidence" standard must be met at the time of entry. The courts may not review proper excercies of discretion but man review any question of law. The government's rule would allow them to stretch the period of "arriving" arbitrarily, and justify the parole if and when it finds a justification. DHS's "mini-trials" is a policy argument without textual support. If DHS wants to remove LPRs it must go through deportation under 1227.
- Lau argues that DHS is using 1182's returning LPR exceptions to evade the procedural requirements of 1227 removal. I find this argument convicing. The government should be going through ordinary deporation proceedings for LPRs. Lau wins.

* Chatrie v United States // https://www.scotusblog.com/cases/chatrie-v-united-states/
* Monsanto Company v Durnell // https://www.scotusblog.com/cases/monsanto-company-v-durnell/
* Cisco Systems, Inc. v Doe I // https://www.scotusblog.com/cases/cisco-systems-inc-v-doe-i/
* Mullin v Doe // https://www.scotusblog.com/cases/noem-v-doe-3/
* Hikma Pharmaceuticals USA Inc. v Amarin Pharma, Inc. // https://www.scotusblog.com/cases/hikma-pharmaceuticals-usa-inc-v-amarin-pharma-inc/ 
