#+title: April

* Sripetch v SEC // https://www.scotusblog.com/cases/case-files/sripetch-v-securities-and-exchange-commission/
- Sripetch bought penny stocks and then promoted them through intermediaries and match traded them to inflate trade volumes. Sripetch was prosecuted and pleaded guilty to sale of unregistered securities. The SEC brough civil-eforcement suit against Sripetch for securities fraud and selling unregistered securities. Sripetch consented to an injunction of future violations and a bar on paticipating in offerings of penny stock. Sripetch did not consent to disgorgement. The SEC is seeking $2.2 million in dosgorgement plus interest. The district court found in favor of SEC. The 9th circuit affirmed on different grounds. Now Sripetch appeals to SCOTUS.
- 78u(d)(3): "Whenever it shall appear to the Commission that any person has violated any provision of this chapter [...] [a] court shall have jurisdiction to (ii) require disgorgement under paragraph (7) of any unjust enrichment by the person who received such unjust enrichment as a result of such violation."
- Sripetch argues that disgorgement is an equitable remedy. Disgorgement restores the status quo by taking the ill-gotten gains from the wrong-doer and returning what was lost to the victims. The victims here have lost nothing (there is no "pecuniary harm") so disgorgement is inappropriate. Disgorgement can't be used as a penalty because it's purpose is compesatory, not punitive. The SEC has other options for seeking penalties; the SEC's theory of disgorgement evades congress's processes and limitations for them.
- The SEC argues that disgorgement does not require proof of pecuniary harm. Disgorgement is based on equity and "it would be quintessentially inequitable to permit a known wrongdoer to profit from his own misdeeds." The text of 78u(d) does not include a pecuniary harm. Other provisions condition remedies on economic loss, the disgorgement provision does not.
- After Liu v SEC congress passed an explicit disgorgement provision (parts of 78u(d)). Sripetch argues that those provisions to codify Liu. The SEC argues that the provisions support their interpretation.
- I should really read Liu before making a prediction. Liu "limited disgorgement to the wrongdoer's net profits and must be awarded for victims" (wikipedia).  After Liu congress passed a law that didn't say anything about the victims. The text of the law seems to clearly empower the court to "require disgorgement [...] of any unjust enrichment" and you don't need pecuniary harm to have been unjustly enriched. SEC wins.

* TM v University of Maryland Medical System Corp. // https://www.scotusblog.com/cases/case-files/t-m-v-university-of-maryland-medical-system-corp/
- TM has a psichiatric condition which she and her private physician attribute to gluten sensitivity. TM signed an advancd directive stating: if she becomes psychotic her Father will become her health-care agent. In 2023 TM had a psychotic episode and was brought to Baltimore Washington Medical Center (BWMC) by police. The hospital staff determined that TM's advance directive was invalid, diagnosed her with schizophrenia and, following a hearing with an ALJ, had her involuntarily admitted over her and her family's objections. The hospital began proceedings to have her injected with a longer lasting form of her antipsychotic medication. TM went to state court to be released from the hospital. TM was able to negotiate a settlement agreement. Under this consent order TM would be released  but must find a new psychiatrist, take her medication, and dismiss her many lawsuits. After being released TM dismissed her other lawsuits but brought another, now challenging the consent order. TM brough an additional lawsuit in Federal court, successfully staying the state court proceedings in the meantime. The district court found, under Rooker-Feldman, that it lacked jurisdiction to challenge the proceedings below at this time. The fourth circuit affirmed and now TM is appealing to SCOTUS.
- TM argues that Rooker-Feldman only applies where statute precludes a district court from reviewing a state-court judgement. Rooker-Feldman comes from 28 USC 1257 which only talks about jurisdiction over appeals from "[f]inal judgments or decrees rendered by the highest court of a State in which a decision could be had" which this is not. Rooker-Feldman is confusing and bad and should be retired.
- UMMS argues that district courts lack jurisdiction to review state court judgements because they were not granted jurisdiction by congress. State court decisions must be appealed through state appellate courts. Once the highest state court has ruled then SCOTUS has jurisdiction to hear appeals. (I don't understand how their argument relies on Rooker-Feldman at all.)
- The facts here seem goofy. What's going on with this lady's psychiatrist? Why was she held involuntarily for so long? But none of this matters here.

