#+title: April

* Sripetch v SEC // https://www.scotusblog.com/cases/case-files/sripetch-v-securities-and-exchange-commission/
- Sripetch bought penny stocks and then promoted them through intermediaries and match traded them to inflate trade volumes. Sripetch was prosecuted and pleaded guilty to sale of unregistered securities. The SEC brough civil-eforcement suit against Sripetch for securities fraud and selling unregistered securities. Sripetch consented to an injunction of future violations and a bar on paticipating in offerings of penny stock. Sripetch did not consent to disgorgement. The SEC is seeking $2.2 million in dosgorgement plus interest. The district court found in favor of SEC. The 9th circuit affirmed on different grounds. Now Sripetch appeals to SCOTUS.
- 78u(d)(3): "Whenever it shall appear to the Commission that any person has violated any provision of this chapter [...] [a] court shall have jurisdiction to (ii) require disgorgement under paragraph (7) of any unjust enrichment by the person who received such unjust enrichment as a result of such violation."
- Sripetch argues that disgorgement is an equitable remedy. Disgorgement restores the status quo by taking the ill-gotten gains from the wrong-doer and returning what was lost to the victims. The victims here have lost nothing (there is no "pecuniary harm") so disgorgement is inappropriate. Disgorgement can't be used as a penalty because it's purpose is compesatory, not punitive. The SEC has other options for seeking penalties; the SEC's theory of disgorgement evades congress's processes and limitations for them.
- The SEC argues that disgorgement does not require proof of pecuniary harm. Disgorgement is based on equity and "it would be quintessentially inequitable to permit a known wrongdoer to profit from his own misdeeds." The text of 78u(d) does not include a pecuniary harm. Other provisions condition remedies on economic loss, the disgorgement provision does not.
- After Liu v SEC congress passed an explicit disgorgement provision (parts of 78u(d)). Sripetch argues that those provisions to codify Liu. The SEC argues that the provisions support their interpretation.
- I should really read Liu before making a prediction. Liu "limited disgorgement to the wrongdoer's net profits and must be awarded for victims" (wikipedia).  After Liu congress passed a law that didn't say anything about the victims. The text of the law seems to clearly empower the court to "require disgorgement [...] of any unjust enrichment" and you don't need pecuniary harm to have been unjustly enriched. SEC wins.
