#+title: December

* Cox Communications, Inc. v Sony Music Entertainment // https://www.scotusblog.com/cases/case-files/cox-communications-inc-v-sony-music-entertainment/
- People use the internet to distribute material in violation of copyright. Rather than suing those individuals Sony sued Cox over its customers' copyright infringement. At trial in E.D. Va. Alexandria. Cox was found liable for "wilfull contributory and vicarious infringement" and Sony was awarded $1 billion. Cox appealed to the 4th circuit which partially upheld the finding of contributory infrigement but reversed on vicarious liability, finding that vicarious liability requires the defendant to profit from the infringement. Cox now appeals to SCOTUS to reverse the verdict or remand for a retrial on a "willfulness standard"
- Cox argues that providing a general-purpose internet connection cannot, without more, support contributory infringement. Contributory liability requires that the defendant (1) knew of the direct infinger's conduct and (2) "intentionally induced or encouraged" it. This is the common-law aiding-and-abetting standard but that is the correct standard here. Cox has an anti-infrigement program which exceeds any test (9th cir., 4th cir.) requiring some measure of prevention. The Plaintiffs complain that they sent Cox complaints about infringing customers but these were unactionable, low quality, and automated. In any case those Judge-made tests violate SCOTUS in Grokster or Twitter (trying to hold Twitter liable for terrorist's use of its service) or Smith & Wesson (trying to hold Smith & Wesson liable for the gun violance using guns they sold).
- Sony (along with many other copyright holders) argue that Cox willfully ignores infringers to continue to profit from their bussiness. The test requiring prevention of copyright isn't merely judge-made; it reflects the safe harbor provision of the DMCA. Cox's program failed to terminate services of specific known infringers. Contributory liability is not aiding-and-abetting and reckless disregard for or willful blindness to infringment does support contributory liability.

* Urias-Orellana v Bondi // https://www.scotusblog.com/cases/case-files/urias-orellana-v-bondi-2/
- Urias-Orellana (along with his wife and child) unlawfully entered the US in 2021. The DHS served him with a notice to appear in immigration court and moved for removal. Urias-Orellana did not contest their removability but sought asylum and protection under CAT. Urias-Orellana had been threatened repeatedly by sicarios (hitmen?) after some of his family members were shot in a protracted dispute. Urias-Orellana eventually moved to another town to avoid them. The Immigration Judge found his testimony credible but unpersuasive. The IJ denied his claim and the Board of Immigration Appeals upheld the decision. Urias-Orellana then appealed to the 1st circuit which, under a substantial evidence standard accepted the ICs findings. Urias-Orellana now appeals to SCOTUS arguing that the 1st circuit should have reviewed the ICs findings de novo.
- Urias-Orellana argues that whether a set of undisputed facts constitutes persecution (the standard for receiving asylum) is a mixed question of law and fact. Determining whether the undisputed facts here meets the legal standard of prosecution is the natural role of article 3 courts.
- DHS argues that this is a predominantly factual question. The IC is best positioned to make such detemintations and the statute makes the most sense leaving article 3 courts to police the outer bounds of such factual detemintaitons.
- Whether a set of facts constitutes persecution is a factual question. Petitioner has some far-too-cute arguments about how Loper Bright requires courts to make independent deteminations as the meaning of this law, but this is not an executive agency exercising rule making authority based on broad statutory grants. Loper Bright does not apply here, DHS wins.

* First Choice Women's Resource Centers, Inc. v Platkin // https://www.scotusblog.com/cases/case-files/first-choice-womens-resource-centers-inc-v-platkin/
- New Jersey has subpoenaed First Choice, a group of faith-based pregnancy centers. The subpoena sought the identites of donors and documents sent to them. First Choice wants to challenge the subpoena in federal court under 1983. The district court first found that the issue wasn't ripe because compliance with the subpoena wasn't ordered by state court. Then the state court ordered compliance with a subpoena. Now the district court finds that the parties don't actually agree on what the subpoena is asking for, there's still no threats forcing compliance, and so it's still not ripe until the state court proceedings proceed (and now you're getting on my nerves, please leave).
- First Choice argues that the issue is ripe because: there is no requirement that they litigate in state court before bringing 1983 claims, losing on constitutional claims in state court would bar them bringing the same claims to federal court (appeal?), the harm of the subpoena has already happened in the form of chilling donor speech, there is an actual and well-founded fear that the subpoena will be enforced.
- Platkin argues that: this investigatory subpoena is not a reasonably objective chill of first amendment speech, the donors' identites haven't yet been ordered released by state court and so might not be, the entire subpoena is actually voluntary (????).
