#+title: December

* Cox Communications, Inc. v Sony Music Entertainment // https://www.scotusblog.com/cases/case-files/cox-communications-inc-v-sony-music-entertainment/
- People use the internet to distribute material in violation of copyright. Rather than suing those individuals Sony sued Cox over its customers' copyright infringement. At trial in E.D. Va. Alexandria. Cox was found liable for "wilfull contributory and vicarious infringement" and Sony was awarded $1 billion. Cox appealed to the 4th circuit which partially upheld the finding of contributory infrigement but reversed on vicarious liability, finding that vicarious liability requires the defendant to profit from the infringement. Cox now appeals to SCOTUS to reverse the verdict or remand for a retrial on a "willfulness standard"
- Cox argues that providing a general-purpose internet connection cannot, without more, support contributory infringement. Contributory liability requires that the defendant (1) knew of the direct infinger's conduct and (2) "intentionally induced or encouraged" it. This is the common-law aiding-and-abetting standard but that is the correct standard here. Cox has an anti-infrigement program which exceeds any test (9th cir., 4th cir.) requiring some measure of prevention. The Plaintiffs complain that they sent Cox complaints about infringing customers but these were unactionable, low quality, and automated. In any case those Judge-made tests violate SCOTUS in Grokster or Twitter (trying to hold Twitter liable for terrorist's use of its service) or Smith & Wesson (trying to hold Smith & Wesson liable for the gun violance using guns they sold).
- Sony (along with many other copyright holders) argue that Cox willfully ignores infringers to continue to profit from their bussiness. The test requiring prevention of copyright isn't merely judge-made; it reflects the safe harbor provision of the DMCA. Cox's program failed to terminate services of specific known infringers. Contributory liability is not aiding-and-abetting and reckless disregard for or willful blindness to infringment does support contributory liability.

* Urias-Orellana v Bondi // https://www.scotusblog.com/cases/case-files/urias-orellana-v-bondi-2/
- Urias-Orellana (along with his wife and child) unlawfully entered the US in 2021. The DHS served him with a notice to appear in immigration court and moved for removal. Urias-Orellana did not contest their removability but sought asylum and protection under CAT. Urias-Orellana had been threatened repeatedly by sicarios (hitmen?) after some of his family members were shot in a protracted dispute. Urias-Orellana eventually moved to another town to avoid them. The Immigration Judge found his testimony credible but unpersuasive. The IJ denied his claim and the Board of Immigration Appeals upheld the decision. Urias-Orellana then appealed to the 1st circuit which, under a substantial evidence standard accepted the ICs findings. Urias-Orellana now appeals to SCOTUS arguing that the 1st circuit should have reviewed the ICs findings de novo.
- Urias-Orellana argues that whether a set of undisputed facts constitutes persecution (the standard for receiving asylum) is a mixed question of law and fact. Determining whether the undisputed facts here meets the legal standard of prosecution is the natural role of article 3 courts.
- DHS argues that this is a predominantly factual question. The IC is best positioned to make such detemintations and the statute makes the most sense leaving article 3 courts to police the outer bounds of such factual detemintaitons.
- Whether a set of facts constitutes persecution is a factual question. Petitioner has some far-too-cute arguments about how Loper Bright requires courts to make independent deteminations as the meaning of this law, but this is not an executive agency exercising rule making authority based on broad statutory grants. Loper Bright does not apply here, DHS wins.

* First Choice Women's Resource Centers, Inc. v Platkin // https://www.scotusblog.com/cases/case-files/first-choice-womens-resource-centers-inc-v-platkin/
- New Jersey has subpoenaed First Choice, a group of faith-based pregnancy centers. The subpoena sought the identites of donors and documents sent to them. First Choice wants to challenge the subpoena in federal court under 1983. The district court first found that the issue wasn't ripe because compliance with the subpoena wasn't ordered by state court. Then the state court ordered compliance with a subpoena. Now the district court finds that the parties don't actually agree on what the subpoena is asking for, there's still no threats forcing compliance, and so it's still not ripe until the state court proceedings proceed (and now you're getting on my nerves, please leave).
- First Choice argues that the issue is ripe because: there is no requirement that they litigate in state court before bringing 1983 claims, losing on constitutional claims in state court would bar them bringing the same claims to federal court (appeal?), the harm of the subpoena has already happened in the form of chilling donor speech, there is an actual and well-founded fear that the subpoena will be enforced.
- Platkin argues that: this investigatory subpoena is not a reasonably objective chill of first amendment speech, the donors' identites haven't yet been ordered released by state court and so might not be, the entire subpoena is actually voluntary (????).
- Look, I guess if the subpoena is entirely voluntary then First Choice should just tell them kick rocks. But obviously they're going to try to enforce the subpoena, what are we waiting for?

* Olivier v City of Brandon, Mississippi // https://www.scotusblog.com/cases/case-files/olivier-v-city-of-brandon-mississippi/
- Olivier is a pastor and prostelitiser in Mississippi. Brandon passed a city ordinance requireing demonstrators to stand in designated protest areas at certain venues. Olivier violated that ordinance and was fined and given a ten-day suspended sentence and a year of unsupervised probation. Months later Olivier claimed the ordinance violates the first amendment and brought a 1983 claim. The district court dismissed his claim because you cannot challenge a statute if your success would invalidate your conviction (Heck v Humphrey). The 5th cir. upheld.
- Olivier argues that the rule against challenging statutes exists to avoid duplicate lawsuits, prisoners going through additional litigation to challenge their convictions, then the law itself. Olivier is looking for protection from future prosecution. Olivier also isn't in custody so can't make a habeas claim which would be the traditional way to make such a challenge. If this ruling is correct the only option is for Olivier to violate the ordinance again.
- Brandon argues that this is a straightforward application of Heck v Humphrey. Applying this rule broadly promotes “federalism, comity, finality, and consistency.”
- Olivier might be SOL, he should've challenged his original conviction but pleaded nolo contendere. Olivier would be able to challenge the case if he were in custody, does it make sense that worse punishments have more chances for challenge? I think so.

* Trump v Slaughter // https://www.scotusblog.com/cases/case-files/trump-v-slaughter-2/
- In March Trump fired FTC commissioner Rebecca Slaughter without cause. The law establishing the FTC protects comissioners from removal except "for inefficiency, neglect of duty, or malfeasance in office". Slaughter challenged her removal in DDC. The DDC ordered her reinstatment and the CADC denied the government's stay pending appeal of that order. Roberts stayed the order pending appeal.
- Slaughter argues that multimember agencies with removal protection have a long history, dating back to the founding. This was affirmed in Hymphrey's Executor which is exactly on point to this case, upholding protections of an FTC commissioner under FDR. Removal protections are also good policy, promoting deliberation and expert judgement, and giving commissioners the ability to alert congress or the public to misbehavior.
  Slaughter argues that while at-will removal is the general rule, and required when officers exercise the Presidents conclusive and preclusive constitutional authorities, congress can create removal protections for traditional independent agencies that implicate an congressional powers.
  Humphrey's Executor is exactly on point. The decision is not egregiously wrong or unworkable, and congress has strong reliance interests in the statutory removal protections that it voted on when establishing dozens of administrative agencies.
- The government argues that all executive power is vested in the president and at-will removal is required for the president to exercise that power.
  Humphrey's Executor rested on the finding that the FTC exercised "no part of the executive power" only "quasi-legislative or quasi-judicial powers". The current FTC creates rules, investigates potential violations, brings enforcement suits, and issues final orders in administrative adjudications. These are core executive powers. Under the logic of Humphrey's the FTC, atleast as it currently operates, is an executive agency and so its leaders must be removable at-will by the president. Also Humphrey's should be overturned because even when it was decided the FTC was an executive agency. "The notion that some agencies that exercise executive power can be sequestered from presidential control seriously offends the Constitution’s structure and the liberties that the separation of powers protects."
- There is a secod qp "whether a federal court may prevent a person's removal from public office". The answer is probably yes, so neither side spends much time on it.
- Alex White at SCOTUSBlog predicts that SCOTUS will uphold the reasoning of Humphrey's Executor, concluding that the FTC did not exercise executive power when the case was decided, but now does.
- The government has the better argument and is more grounded in recent precedent like Seila Law. The policy argument is unlikely to be convicing to a majority of the court (even if they agree with it which they probably don't). I find the Congressional reliance interests argument their strongest point but it won't to carry them over the finish (govt cites Chadha striking down the legislative veto, included "in nearly 200 statues"). Please anyone but Roberts write this opinion!

* National Republican Senatorial Committee v FEC // https://www.scotusblog.com/cases/case-files/national-republican-senatorial-committee-v-federal-election-commission/
- The statute establishing the FEC limits "coordinated party expenditures", that is money that a political party can spend on a member's campaign with their input, at $10k, $20k, or $0.02 * voter pop. Republicans say that violates the first amendment and challenged it in CA6 (constitutional challenges to campaign finance get to skip steps). The 6th circuit found that the previous case challenging this exact rule concluded with SCOTUS upholding the rule. The 6th circuit also found that they are bound by precedent. So now republicans appeal to SCOTUS asking them to try again and probably overturn FEC v. Colo. Republican Fed. Campaign Comm. (Colorado II) . The government and republicans are on the same side so SCOTUS appointed an Amicus Curiae Roman Martinez. There is also a second red brief from the DNC.
- Respondents argue that: (1) plaintiffs Vance and Chabot lack standing because the FEC is declining to enforce this provision (believing it unconstitutional) and neither are currently running or plan to run for office and (2) Colorado II was not egregeously wrong, there is a compelling government interest in these limits in preventing donors from donating in excess of limits through the parties, and this would give parties special privilege to donate without limit.
- Plaintiffs argue that limits to political speech can only survive if they are narrowly tailored to prevent quid pro quo corruption. These limits were meant to reduce campaign spending by parties and make no sense as corruption prevention.
- Awkward vehicle and there's an easy out to avoid the question. But the court has been moving in this direction. I'm curious what they make of the party privilege argument.
