#+title: December

* Cox Communications, Inc. v Sony Music Entertainment // https://www.scotusblog.com/cases/case-files/cox-communications-inc-v-sony-music-entertainment/
- People use the internet to distribute material in violation of copyright. Rather than suing those individuals Sony sued Cox over its customers' copyright infringement. At trial in E.D. Va. Alexandria. Cox was found liable for "wilfull contributory and vicarious infringement" and Sony was awarded $1 billion. Cox appealed to the 4th circuit which partially upheld the finding of contributory infrigement but reversed on vicarious liability, finding that vicarious liability requires the defendant to profit from the infringement. Cox now appeals to SCOTUS to reverse the verdict or remand for a retrial on a "willfulness standard"
- Cox argues that providing a general-purpose internet connection cannot, without more, support contributory infringement. Contributory liability requires that the defendant (1) knew of the direct infinger's conduct and (2) "intentionally induced or encouraged" it. This is the common-law aiding-and-abetting standard but that is the correct standard here. Cox has an anti-infrigement program which exceeds any test (9th cir., 4th cir.) requiring some measure of prevention. The Plaintiffs complain that they sent Cox complaints about infringing customers but these were unactionable, low quality, and automated. In any case those Judge-made tests violate SCOTUS in Grokster or Twitter (trying to hold Twitter liable for terrorist's use of its service) or Smith & Wesson (trying to hold Smith & Wesson liable for the gun violance using guns they sold).
- Sony (along with many other copyright holders) argue that Cox willfully ignores infringers to continue to profit from their bussiness. The test requiring prevention of copyright isn't merely judge-made; it reflects the safe harbor provision of the DMCA. Cox's program failed to terminate services of specific known infringers. Contributory liability is not aiding-and-abetting and reckless disregard for or willful blindness to infringment does support contributory liability.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-171_bq7d.pdf
- Thomas, writing for a unanimous court, finds that Cox is no liable for infringemet of Sony's copyrights. Pecedents predating the Copyright Act recognize narrow forms of secondary liability. But, "we are loath to expand such liability". Contributory liability exists when service provider intends its service to be used to infringe. The provider must induce that infringement or tailor its service to infringement. Knowlege that a service will be used for infringement is not enough. Failure to terminate service to infringers is not enough. The DMCA creates a safeharbor as a defense from liability, it does not create new liability.
- Sotomayor, joined by Jackson, writes separately arguing that Thomas reads secondary liability too narrowly. The concurrence agrees that Cox cannot be held liable here.

* Urias-Orellana v Bondi // https://www.scotusblog.com/cases/case-files/urias-orellana-v-bondi-2/
- Urias-Orellana (along with his wife and child) unlawfully entered the US in 2021. The DHS served him with a notice to appear in immigration court and moved for removal. Urias-Orellana did not contest their removability but sought asylum and protection under CAT. Urias-Orellana had been threatened repeatedly by sicarios (hitmen?) after some of his family members were shot in a protracted dispute. Urias-Orellana eventually moved to another town to avoid them. The Immigration Judge found his testimony credible but unpersuasive. The IJ denied his claim and the Board of Immigration Appeals upheld the decision. Urias-Orellana then appealed to the 1st circuit which, under a substantial evidence standard accepted the ICs findings. Urias-Orellana now appeals to SCOTUS arguing that the 1st circuit should have reviewed the ICs findings de novo.
- Urias-Orellana argues that whether a set of undisputed facts constitutes persecution (the standard for receiving asylum) is a mixed question of law and fact. Determining whether the undisputed facts here meets the legal standard of prosecution is the natural role of article 3 courts.
- DHS argues that this is a predominantly factual question. The IC is best positioned to make such detemintations and the statute makes the most sense leaving article 3 courts to police the outer bounds of such factual detemintaitons.
- Whether a set of facts constitutes persecution is a factual question. Petitioner has some far-too-cute arguments about how Loper Bright requires courts to make independent deteminations as the meaning of this law, but this is not an executive agency exercising rule making authority based on broad statutory grants. Loper Bright does not apply here, DHS wins.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-777_9ol1.pdf
- Jackson, writing for a unanimous court, affirms in favor of DHS. 1252(b)(4)(B) (the section at issue here) "provides that the administrative findings of fact are conclusive unless any reasonable adjudicator would be compelled to conclude to the contrary." This was correctly understood to be a "substantial evidence" standard: that is that the finding will be affirmed "unless any reasonable adjudicator would be compelled to conclude to the contrary." This statute was already interpreted in INS v Elias-Zacarias. The court in Elias-Zacarias did not use the term "substantial evidence" but the standard described there is what we're now calling "substantial evidence". The law has since changed (INS is now DHS) but its current text ("no reasonable factfinder could fail to find ...") calls for the same standard. If anything congress has been making immigration appeals harder construing the change in the law here to make them easier doesn't make sense.

* First Choice Women's Resource Centers, Inc. v Platkin // https://www.scotusblog.com/cases/case-files/first-choice-womens-resource-centers-inc-v-platkin/
- New Jersey has subpoenaed First Choice, a group of faith-based pregnancy centers. The subpoena sought the identites of donors and documents sent to them. First Choice wants to challenge the subpoena in federal court under 1983. The district court first found that the issue wasn't ripe because compliance with the subpoena wasn't ordered by state court. Then the state court ordered compliance with a subpoena. Now the district court finds that the parties don't actually agree on what the subpoena is asking for, there's still no threats forcing compliance, and so it's still not ripe until the state court proceedings proceed (and now you're getting on my nerves, please leave).
- First Choice argues that the issue is ripe because: there is no requirement that they litigate in state court before bringing 1983 claims, losing on constitutional claims in state court would bar them bringing the same claims to federal court (appeal?), the harm of the subpoena has already happened in the form of chilling donor speech, there is an actual and well-founded fear that the subpoena will be enforced.
- Platkin argues that: this investigatory subpoena is not a reasonably objective chill of first amendment speech, the donors' identites haven't yet been ordered released by state court and so might not be, the entire subpoena is actually voluntary (????).
- Look, I guess if the subpoena is entirely voluntary then First Choice should just tell them kick rocks. But obviously they're going to try to enforce the subpoena. What are we waiting for?
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-781_pok0.pdf
- Gorsuch, writing for a unanimous court, finds that First Choice has standing. The first amendment rights of expression, religion, and petition contain a right to associate with others. Demands of private donor information infringe on that right. Such demands are especially suspect when, as here, the private donors are supporting a policy position contrary to those in power. In order to infringe upon such rights the government action must satisfy heightened 1st amendment scrutiny. New Jersey's demands of private donor information burden First Choice's 1st amendment rights and do not satisfy heightened scrutiny. It does not matter that the subpoena is not self-executing. A plaintiff does not need to wait for the state courts to compel compliance. It does not matter that the subpoena carves out a single method of donation that can remain private. It does not matter that the state promises to keep the donor information out of the public. First Choice was injured by Platkin's subpoena and may bring a claim under 1983 in federal court.

* Olivier v City of Brandon, Mississippi // https://www.scotusblog.com/cases/case-files/olivier-v-city-of-brandon-mississippi/
- Olivier is a pastor and prostelitiser in Mississippi. Brandon passed a city ordinance requireing demonstrators to stand in designated protest areas at certain venues. Olivier violated that ordinance and was fined and given a ten-day suspended sentence and a year of unsupervised probation. Months later Olivier claimed the ordinance violates the first amendment and brought a 1983 claim. The district court dismissed his claim because you cannot challenge a statute if your success would invalidate your conviction (Heck v Humphrey). The 5th cir. upheld.
- Olivier argues that the rule against challenging statutes exists to avoid duplicate lawsuits, prisoners going through additional litigation to challenge their convictions, then the law itself. Olivier is looking for protection from future prosecution. Olivier also isn't in custody so can't make a habeas claim which would be the traditional way to make such a challenge. If this ruling is correct the only option is for Olivier to violate the ordinance again.
- Brandon argues that this is a straightforward application of Heck v Humphrey. Applying this rule broadly promotes “federalism, comity, finality, and consistency.”
- Olivier might be SOL, he should've challenged his original conviction but pleaded nolo contendere. Olivier would be able to challenge the case if he were in custody, does it make sense that worse punishments have more chances for challenge? I think so.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-993_10n2.pdf
- Kagan, writing for a unanimous court, finds that Olivier's suit can proceed because it seeks only prospective relief. The Heck bar stops 1983 claims from contradicting Habeas. Habeas can't be used to obtain prospective releif so prospective releif is not barred by Heck. Brandon overreads dicta in Heck to expand the decision.
- The dicta in Heck is probably just a mistake. "[W]hen a state prisoner seeks damages in a §1983 suit, the district court must consider whether a judgment in favor of the plaintiff would necessarily imply the invalidity of his conviction or sentence; if it would, the complaint must be dismissed". Read plainly this applies to Olivier. Kagan writes, "the sentence relied on swept a bit too broad".

* Trump v Slaughter // https://www.scotusblog.com/cases/case-files/trump-v-slaughter-2/
- In March Trump fired FTC commissioner Rebecca Slaughter without cause. The law establishing the FTC protects comissioners from removal except "for inefficiency, neglect of duty, or malfeasance in office". Slaughter challenged her removal in DDC. The DDC ordered her reinstatment and the CADC denied the government's stay pending appeal of that order. Roberts stayed the order pending appeal.
- Slaughter argues that multimember agencies with removal protection have a long history, dating back to the founding. This was affirmed in Hymphrey's Executor which is exactly on point to this case, upholding protections of an FTC commissioner under FDR. Removal protections are also good policy, promoting deliberation and expert judgement, and giving commissioners the ability to alert congress or the public to misbehavior.
- Slaughter argues that while at-will removal is the general rule, and required when officers exercise the Presidents conclusive and preclusive constitutional authorities, congress can create removal protections for traditional independent agencies that implicate congressional powers.
- Humphrey's Executor is exactly on point. The decision is not egregiously wrong or unworkable, and congress has strong reliance interests in the statutory removal protections that it voted on when establishing dozens of administrative agencies.
- The government argues that all executive power is vested in the president and at-will removal is required for the president to exercise that power.
- Humphrey's Executor rested on the finding that the FTC exercised "no part of the executive power" only "quasi-legislative or quasi-judicial powers". The current FTC creates rules, investigates potential violations, brings enforcement suits, and issues final orders in administrative adjudications. These are core executive powers. Under the logic of Humphrey's the FTC, atleast as it currently operates, is an executive agency and so its leaders must be removable at-will by the president. Also Humphrey's should be overturned because even when it was decided the FTC was an executive agency. "The notion that some agencies that exercise executive power can be sequestered from presidential control seriously offends the Constitution’s structure and the liberties that the separation of powers protects."
- There is a secod qp "whether a federal court may prevent a person's removal from public office". The answer is probably yes. Neither side spends much time on it.
- Alex White at SCOTUSBlog predicts that SCOTUS will uphold the reasoning of Humphrey's Executor, concluding that the FTC did not exercise executive power when the case was decided, but now does.
- The government has the better argument and is more grounded in recent precedent like Seila Law. The policy argument is unlikely to be convicing to a majority of the court (even if they agree with it which they probably don't). I find the Congressional reliance interests argument their strongest point but it won't to carry them over the finish (govt cites Chadha striking down the legislative veto, included "in nearly 200 statues"). Please anyone but Roberts write this opinion!
** opinion // https://www.supremecourt.gov/opinions/25pdf/25-332_qn12.pdf
- Roberts, joined by Thomas*, Alito, Gorsuch, Kavanaugh, and Barrett, reverses in favor of Trump. Executive officers must be removable by the President so that they remain accountable to the President. This was the understanding of the founders and the practice for the country's history. In 1876 the supreme court agreed, striking a law which required senate approval to remove post masters. In Humphrey's Executor the court upheld removal protections for the FTC. The court found that the FTC did not exercise executive power and so could safely be insulated from the President's removal power. Humphrey's was wrongly decided. The FTC did and does exercise executive power. Humphrey's has be narrowed to its facts; rarely applied to other agencies. It has proven unworkable with recent contrary precedent. The only reliance interest is in Congress's laws which create officers free from Presidential oversight. Congress doesn't get reliance interests on power it takes from the President. Humphrey's Executor is overturned.
- The FTC has rule making power. The FTC investigates and enforces rules with penalties. The FTC brings civil suits on behalf of the United States. These are executive powers. The FTC's officers must be removable by the President so they remain accountable to the President.
- Gorsuch concurrs to argue that many agencies intrude on legislative and judicial powers as well as executive. Executive agencies, now answerable to the president, give the executive too much power. Congress and the court must unwind the powers the President has accumulated.
- Sotomayor, joined by Kagan and Jackson, dissents, arguing that the constitution allows Congress to create independent agencies with for-cause removal protections. The constitution does not speak clealy to the issue, which is why the majority needs to look at commentary and private correspondence of the founders. In the meentime practice has sanctioned more than just the FED. Congress has created dozens of agencies with removal protections. The President has signed the laws and the court has upheld them. These laws and their long history sanction the practice.
** commentary
- https://www.execfunctions.org/p/sai-prakash-on-slaughter-and-cook
  Goldsmith and Prakash disagree on how farm Slaughter goes. Prakash predicts removal powers will extend past agency heads--inferior officers, prosecutors and ALJs. Goldsmith doesn't see Robert's opinion as reaching that. Both agree that civil service employees aren't touched on (atleast as long as they aren't doing prosecution, rulemaking, or internal ajudication).
- Prakash argues that agencies are not very independant. Goldsmith argues that the less high profile agencies and the lower level employees take more to control.
- Goldsmith and Prakash agree that the FED exception is weak.
-

* National Republican Senatorial Committee v FEC // https://www.scotusblog.com/cases/case-files/national-republican-senatorial-committee-v-federal-election-commission/
- The statute establishing the FEC limits "coordinated party expenditures", that is money that a political party can spend on a member's campaign with their input, at $10k, $20k, or $0.02 * voter pop. Republicans say that violates the first amendment and challenged it in CA6 (constitutional challenges to campaign finance get to skip steps). The 6th circuit found that the previous case challenging this exact rule concluded with SCOTUS upholding the rule. The 6th circuit also found that they are bound by precedent. So now republicans appeal to SCOTUS asking them to try again and probably overturn FEC v. Colo. Republican Fed. Campaign Comm. (Colorado II) . The government and republicans are on the same side so SCOTUS appointed an Amicus Curiae Roman Martinez. There is also a second red brief from the DNC.
- Respondents argue that: (1) plaintiffs Vance and Chabot lack standing because the FEC is declining to enforce this provision (believing it unconstitutional) and neither are currently running or plan to run for office and (2) Colorado II was not egregeously wrong, there is a compelling government interest in these limits in preventing donors from donating in excess of limits through the parties, and this would give parties special privilege to donate without limit.
- Plaintiffs argue that limits to political speech can only survive if they are narrowly tailored to prevent quid pro quo corruption. These limits were meant to reduce campaign spending by parties and make no sense as corruption prevention.
- Awkward vehicle and there's an easy out to avoid the question. But the court has been moving in this direction. I'm curious what they make of the party privilege argument.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-621_h315.pdf
- Kavanaugh, joined by Roberts, Thomas, Alito, Gorsuch, and Barrett, rule the coordinated spending limits unconstitutional in favor of NRSC. Contribution limits are subject to closely drawn scrutiny (McCutcheon and Cruz). Such limits must be proportionate, necessary, and narrowly tailored to its goal. There are two justifications: quid pro quo corruption and circumvention. Amicus argues that coordination limits are neccessary to prevent circumvention. RNC argues that a limit is not narrowly tailored when disclosure and earmarking rules would suffice. Without earmarking donors cannot pay candidates through their party. Earmarking and disclosure rules will require more resources to enforce but the government cannot suppress speech because it's easier for them. The experience of state without these rules do not show sufficient risk of corruption. Therefore the coordinated spending rules are disproportionate, unnecessary, and not narrowly tailored.
- The court overrules Colorado II. Stare decisis is weakest at constitutional interpretation. Colorado II was wrong to allow "unskillful tailoring" and the court has since required more from closely drawn scrutiny. Colorado II was wrong to restrict party spending as "undue influence" because political partys exist to support policies and endorse candidates, there is nothing "undue" about that influence. Colorado II also displaced spending from candidates to Super PACs. The only reliance interest here is that of outside groups, advantaged over political parties who cannot spend as they wish. This does not justify maintaining "an egregiously wrong precedent".
- The case is not moot. Even if the FEC declines to encforce the limits, FECA provides for private suits. Vance's "Statement of Candidacy" indicates an intent to run for Senate in 2028, giving him standing.
- Kagan, joined by Sotomayor and Jackson, dissents arguing that coordinated spending is special and justifies statutory limits. In practice candidates group with national and regional parties to accept donations much larger than any single limit (on the order of $500,000). Those larger donations can be passed through to the national party. Any coordinated spending can be used to pay the campaign's bills, making it as good as cash. So if we allow coordinated spending between the party and the candidate then a donor can pay far in excess of the individual contribution limit ($7000). Parties are incetivized to pass those contributions on to the candidates who raised them and so corrupt donors are incentivized to make those donations in exchange for official acts.

* Hamm v Smith // https://www.scotusblog.com/cases/case-files/hamm-v-smith-4/
- https://caselaw.findlaw.com/court/al-court-of-criminal-appeals/1096178.html
- Joseph Clifton Smith was released from prison for robbery and parole violations in november 1997. Two days later he and a friend robbed and murdered a man next to his truck. For his part in the murder Smith was sentenced to death. Smith argued tha the cannot be sentenced to death because he is intellectually disabled. Atkins v Virginia found that it violates the 8th amendment to execute people with intellectual disabilities. The district court SDAl. found that Smith is intellectually disabled, rejecting the sentence. The 11th circuit upheld the decision. The prosecution appealed to SCOTUS and after some ping ponging for more explaination SCOTUS granted cert. The qp is specifically asking how "multiple IQ scores" interact with Atkins claims. Alabama law sets a nominal bar at 70 iq, Smith took 5 iq tests and the lowest was 72 with an error of 3.
- The State (Hamm is Alabama's Commissioner of Dept. of Corrections) argues that there's no uniformity in how different states consider multiple scores. In any case a single score of 78 should foreclose a finding of intellectual disability. The court should have a presumption in favor of the sentence because psychaiatry does not yield definite rigorous results.
- Smith argues that in light of unclear IQ tests additional context becomes even more important. The lower courts correctly looked at school records, medical records, behavior, personal history, and other psychiatric tests to find that Smith is intellectually disabled.
- 72 is greater than 70, bang the gavel PepeMods .
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-872_ec8f.pdf
- PC: DIGed
- Sotomayor concurrs, arguing that states and lower courts should have flexibility in how to determine intellectual disability under Atkins. Absent a circuit split SCOTUS's guidence isn't needed. And this is a poor vehicle for determining guidence.
- Thomas dissents, arguing that Atkins isn't supported by the text of the 8th amendment and so should be overturned.
- Alito dissents, arguing that Atkins has proven unworkable and the court must provide more guidence.

* FS Credit Opportunities Corp. (The Fund) v Saba Capital Master Fund Ltd. (The Investors) // https://www.scotusblog.com/cases/case-files/fs-credit-opportunities-corp-v-saba-capital-master-fund-ltd/
- FS Credit has a provision limiting voting to shareholders unless approved by 2/3rds of shareholders. Saba sued FS Credit alledging that this violates the Investment Company Act. The ICA states that all new stock must be voting and have equal voting rights to all other outstanding stock. The district court for SDNY granted summary judgement in favor of Saba and the CA2 affirmed. FS Credit is appealing to SCOTUS arguing that the ICA does not provide such a private right of action.
- FS Credit argues that the rulings below are following old precedent which incorrectly found private rights of action everywhere. This provision does not clearly create a private right of action, therefore none exists. It is the SECs job to enforce the ICA. Finding an implied right of action in this statute would be especially wrong because the same statute does create private rights of action, just not for this provision.
- Saba points to precedent involving a related statute. Transamerica Mortgage Advisors (TAMA) which found in favor of a private right of action in the Investment Advisers Act. Saba says the language, "a court may not deny rescission at the instance of any party" creates a private right of action to rescind the offending voting rule.
- I really feel like we're stretching the "clear grant of a private right of action" but I felt the same way about the last 4 cases. The Fund probably wins.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-345_i42k.pdf
- Barrett, joined by Roberts, Thomas, Alito, Gorsuch, and Kavanaugh, reverse the 2nd circuit in favor of the fund. The Investment Company Act generally empowers the SEC to bring enforcement actions. Twice it creates a private right of action for share holders but not here.
- 47(b) allows rescission "at the instance of any party." But this refers to any part to an existing suit. It does not create a new right of action for any party anywhere.
- Much ink relitigates the merits of implied rights of action and legislative history. The conservatives argue that when congress wants to create a private right of action they use specific language ("a civil action [...] may be instituted by the person aggrieved" 42usc 2000a-3). It's congress's job to create such rights, the court would overstep to find one here. The legislative history favored by the liberals is cherry picked and inevitably so because there's lots of legislative history written by lots of people. The legislators only agreed on the statute which is what the court must interpret.
- Jackson, joined by Sotomayor and Kagan*, find that the court's precedent in TAMA and the stautory history balance in favor of finding a private right of action. TAMA interpreted the preamended ICA language and found a private right of action. Congress was aware of TAMA and enacted the amendment with knowledge of it and the new language is stronger. The "any party" language should be read capaciously, applying to any party to existing litigation or contract.
- Jackson reads the Committee reports as showing congress's intent to create private rights of action. ("private lawsuits serve as an added deterrent to conduct made unlawful by Congress, without the necessity of governmental involvement.") The committee thought TAMA was too conservative in finding private rights of action. The court should take that as the hint that congress expects more not fewer private rights of action. These congressional reports are the context in which the statute was written and give insight into congressional intent. Reading congressional reports for the context of a statute is like reading the ratification debates or the federalist papers to better understand the framers. This is why legislative history was used for so long.
- Kanag joined Jackson's dissent on the statutory interpretation but not on the fighting about legislative history.
