#+title: February

* Havana Docks v Royal Carribean Cruises // https://www.scotusblog.com/cases/case-files/havana-docks-corporation-v-royal-caribbean-cruises-ltd/
- In 1905 Cuba made an agreement with Havana Docks. Havana Docks would build a pier and terminal building in Havana Harbor. In exchange Havana Docks would have rights to the harbor for some time. Ultimately Havana Docks built 3 piers and 3 terminal buildings that they would have rights to for 99 years. In 1960 (following the Cuban Revolution) Cuba expropriated the assets of Havana Docks. Cuba did not compesate Havana Docks "for the value of all works" as was required by their agreement. Havana Docks received a certified claim of $9.18 million in 1971 (with interest nearly $100m) at the Foreign Claims Settlement Commission. As part of the Helms-Burton act (1996) congress expanded sanctions on Cuba and allowed plaintiffs with a claim a private right of action against those trafficking in expropriated assets. Such claims remained unavailable while suspended by the president until 2019. Since 2015 Cruise lines have been bringing tourists to the expropriated docks. Havana Docks sued in District Court (S.D.Fl.) and won big! The Cruise lines then appealed to the 9th Circuit. The 9th circuit reversed finding that by the time the cruise lines trafficked in the expropriated assets (used the ports) Havana Dock's 99 years were up.
- Havana Docks argues that Helms-Burton grants a private right of action for any traficking of confiscated property. Their property was confiscated and the cruise lines trafficked in it. Once property is confiscated it remains confiscated and cannot be trafficked in until its rightful owner is compensated.
- The cruise lines argue that: They were liscenced by the government to travel to Cuba; The Cuban government wouldn't allow them to disembark except at the dock (the law has an exception for transactions which are "necessary to the conduct of [lawful] travel"); and that HDC's property interest had ended by the time the cruise liners used the docks. The cruise liners argue that the "trafficked proprety" is really Havana Dock's concession (their rights to make money from the docks) and not the docks themselves.

* Exxon Mobil v Corporacion Cimex, S.A. // https://www.scotusblog.com/cases/case-files/exxon-mobil-corp-v-corporacion-cimex-s-a/
- In the early 1900s Standard Oil (Now Exxon Mobil) did bussiness in Cuba. This involved building refineries, product terminals, and service stations. On June 29, 1960 the Cuban government expropriated this property and gave it to their state owned oil companies. The FCSC certified Exxon's claim for $71m (with interest now over $1b). Under the Helms-Burton act Exxon is suing Cimex (The Cuban SOE that was given their property). The Distrcit court found that defendants (instrumentatlities of a foreign sovereign) are entitled to foreign sovereign immunity, and that only one defendant fell within an exception and could be sued. On appeal the circuit court found that all the defendants were protected by foreign sovereign immunity.
- Exxon argues that the Helms-Burton act displaces the Foreign Sovereign Immunities Act. The Helms-Burton act "speak[s] clearly to withdraw sovereign immunity." The Helms-Burton act holds liable "any person that [...] traffics in property which was confiscated by the Cuban Government" and defines "person" to include "any agency or instrumentatlity of a foreign state" (22.6082, 22.6023).
- The point of the law is to let people sue over property confiscated by Cuba. Most of the property was taken in Cuba and given to SOEs. Requiring suits to also fall under an FSIA exception would stop most of the claims the law is inteded to allow. The law elsewhere refers to judgements against Cuban instrumentatlities. It then makes those judgements unenforcable against a transition government. 
- Cimex argues Helms-Burton act title 3 claims can only be brought against state instrumentatlities if they fall within an exception to Foreign Sovereign Immunity. Congress could have amended the FSIA as part of the act, as they've done with other acts and as they proposed to do before objections. Congress chose not to. Under Kirtz "immunity is not abrogated if any plausible interpretation of the statute would preserve it" (Brief for Resp.). The interpretation petitioners argue for is broad, it would waive immunity for any instrumentatlities, not just Cuban ones.

* Enbridge Energy, LP v Nessel // https://www.scotusblog.com/cases/case-files/enbridge-energy-lp-v-nessel/
- Enbridge Energy operates the Line 5 pipeline which transports fuels between Wisconsin, Michigan, and Ontario. Michigan (Dana Nessel is the AG of Michigan) claims that the section of the pipeline that crosses the Straits of Mackinac is at risk of causing environmental harm. in June 2019 Nessel went to state court to enjoin its use. In November 2020 Michigan Governor Gretchen Whitmer brought another suit which Enbridge successfully removed to federal court. Whitmer then voluntarily dismissed her case to avoid an unfavorable ruling from the federal court which might override the state court. Enbridge then wanted to remove the Nessel case arguing that the 30-day deadline for such removals should be tolled. The district court agreed. On appeal the 6th circuit reversed, and now Enbridge is appealing to SCOTUS.
- Enbridge argues that equitable tolling is the default and 1446(b)(1) does nothing to indicate that it's unavailable here. The statute uses the same language as other deadline statutes. Absent specific language a deadline should only be read to disallow tolling if the deadline is "unusually generous"--30 days is not unusually generous.
- Michigan argues that equitable tolling is only the default in statutes of limitations. Deadlines for motions made after the plaintiff files are not presumptively subject to tolling. Michigan also argues that the text of 1446(b) weighs against tolling. 1446(b) reads that a notice of removal "*shall* be filed within 30 days." 1446(b) also includes explicit exceptions to the 30-day deadline. If congress wanted to allow equitable tolling they would have wrote it there.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-783_bqm2.pdf
- Sotomayor, writing for a unanimous court, finds that the explicit exceptions to 1446(b)(1)'s deadline forecloses the implied exceptions hadled by equitable tolling. Statutes of limitations come with a presumption of equitable tolling. Granting that this is a statute of limitations, "the presumption is reutted if there is good reason to believe Congress did not want the equitable tolling doctrine to apply." 1446(b)(1)'s time limit has a number of statutory exceptions. 1446(b) allows exceptions for cause. 1454(b)(2) allows exceptions for certain intellectual-property rights. 1441(e)(1) allows the district court to grant leave for certain cases involving fatal accidents. These provisions already account for the equity principles equitable tolling is meant to handle. If equitable tolling was available these exceptions would be redundant.
- 1455(b)(1) is a similar law related to removal of criminal cases. Congress wrote in 1455 that "for good cause shown the [...] court may [grant] the defendant [...] leave to file the notice at a later time." This is what a statute that calls for equitable tolling looks like.
- Footnote 2 mentions that Enbridge brought a separate action to federal court in 2020. "[I]n December 2025, the District Court granted summary judgment to Enbridge".

* Pung v Isabella County, Michigan // https://www.scotusblog.com/cases/case-files/pung-v-isabella-county-michigan/
- In 2008, After the death of his mother, Marc Pung inhereted and continued to live in his family's home. Marc Pung failed to submit an affidavit that the home was his primary residence so in 2010 the county retroactively revoked his primary residence exception leaving him with unpaid taxes. During litigation Pung refused to pay the extra tax. In February 2015 the state court found that Pung was entitled to the PRE. Michigan then foreclosed on the home and sold it years later for $76k to cover the $2k tax bill. The fair market value of the home (outside of a forced auction) was $194k. Pung's suit ended up in W.D.Mich. which held that he was entitled only to the surplus of the $76k sale. On appeal the 6th circuit upheld and now Pung is appealing to SCOTUS.
- Pung argues that the Takings Clause requires that he is compensated based on the fair market value of his property. Allowing compensation based on a depressed price incentivises the government to sell property with no excess. The loss is also effectively a fine in violation of the 8th amendment. Pung lost $118k due to a $2k tax dispute.
- Michigan argues that forclosure to collect on delinquent taxes has been the historical practice for centuries. After a sale the excess money is returned to the former owner. There is no history of the fair market value being used. The fair market value is inapplicable in foreclosure because it inevitable lowers the sale price. Requiring the governent to pay back the fair market value would leave the government at a deficit, making foreclosure an unusable tool. The 8th amendment is inapplicable here because foreclosures are done in rem (the property is the defendant). The original owner is not part of the proceeding and so this is not a fine.
  
* US v Hemani // https://www.scotusblog.com/cases/case-files/united-states-v-hemani/
- In 2020 Hemani became the subject of an FBI investigation based on ties to Iranian terrorism. The FBI got a warrant and searched Hemani's home. The FBI found drugs and a gun in his home. The FBI charged Hemani under 18 USC 922(g)(3) for possessing a firearm as an unlawful user of a controlled substance. Hemani moved to dismiss the case, arguing that 922(g)(3) violates his right to bear arms. The district court agreed and dismissed the charge. The Fifth Circuit affirmed the dismissal and now the government is appealing to SCOTUS.
- Hemani argues that 922(g)(3) vioaltes the right to bear arms and is unconstitutionally vague. 922(g)(3) makes it a crime to be an "unlawful user" but does not define what makes a use "unlawful". The government wants to replace "lawful" with "habitual" but (1) those are different words and (2) If Hemani is a habitual user then anyone who has an alchoholic drink with dinner each night is also. Analogies to founding era habitual drunkard laws do not apply because habitually getting drunk is not habitual use. There is no evidence in the record that speaks to Hemani abusing marijuana, just him using it regularly as many Americans do.
- The government argues that the government can disarm habitual drug users. Habitual drunkard laws have long allowed the state to diarm individuals even while presently sober. 922(g)(3) is correctly tailored to apply only to habitual users. Habitual drug users pose a particular danger. Rahmimi upheld the disarming of the subject of a domestic restraining order for being dangerous. Heller (in dicta) presumed lawful the disarming of felons and the mentally ill.
- Very skeptical of the government's position here. A lot of good facts going for Hemani, nothing showing he's abusing, nothing showing it negatively affects him or those around him, nothing showing dependency. This all makes the beer-with-dinner analogy seem strong. I predict Hemani wins here, probably SCOTUS makes some new law and kicks it down to the trial court for facts.

* Hunter v US // https://www.scotusblog.com/cases/case-files/hunter-v-united-states-2/
- Munson Hunter pleaded guilty to fincancial fraud. As part of his plea agreement Hunter must take any medication prescribed by his physician. As part of the same plea agreement Hunter agreed to waive his right to appeal. Hunter appealed the medication condition of his plea agreement to the Fifth Circuit. The Fifth Circuit allows two exceptions to an appeal waiver: (1) ineffective assistance of council and (2) a sentence exceeding the statutory maximum. This is neither of those so kick rocks. Hunter is now appealing that decision to SCOTUS.
- Hunter argues that he cannot waive his right to appeal unforeseeable punishments. The Fifth circuit's statutory maximum exception comes from unforeseeability but so too does his medication condition. The Fifth Circuit's strict rule makes ridiculous sentences unappealable: sentences to torture, sentences based on race, sentences that impose religious action. Hunter should also be allowed to appeal because the sentencing Judge told him he could and the prosecution did not object. This should be understood as a verbal amendment or waiver of the waiver, allowing him to appeal.
- The government argues that appeal waivers are good and should remain reliable. Appeal waivers support finality and judicial efficiency. Appeal waivers will be less valuable in negotiation if they can be circumvented. The sentence in this case is not ridiculous and was not unforeseeable--requiring someone with a mental-health history to take all prescribed medication is a common supervised-release condition. The judge's statement was literally true because he does have some right to appeal. The judge's statement cannot by itself modify the plea agreement and a party's lack of objection is not agreement to modification and it would have to be in writing anyway.
- I have no prediction on this one. I don't have enough background on how strictly we enforce contracts. I'm leaning toward Hunter only because priors + other circuits.

* Montgomery v Caribe Transport II // https://www.scotusblog.com/cases/case-files/montgomery-v-caribe-transport-ii-llc/
- Robinson (Caribe Transport is the first named defendant but this appeal realtes to Robinson's liability) is a freight broker, they arrange for freight transport by hiriing motor carriers (truckers). Robinson hired Caribe Transport. Varela-Mojena, a Caribe employee, hit Montgomery on the side of the road. Montgomery was injured and required surgery including the amputation of his leg below the knee. Montgomery went to District Court S.D.Il. in 2019. He brought state law claims against Varela-Mojena, Cribe Transport, and Robinson. Robinson moved to dismiss because the Federal Aviation Administration Authorization Act, FAAAA, preempts the negligent-hiring claims against him. The District Court agreed and the Seventh Circuit affirmed. Now Montgomery is appealing to SCOTUS.
- 14501(c)(1) (The Preemption Provision https://www.law.cornell.edu/uscode/text/49/14501#:~:text=General%20rule): a State [...] may not enact or enforce a law, regulation, or other provision having the force and effect of law related to a price, route, or service of any motor carrier [...] or any motor private carrier, broker, or freight forwarder with respect to the transportation of property.
- 14501(c)(2)(a) [Above] shall not restrict the safety regulatory authority of a State with respect to motor vehicles [...]
- Montgomery argues that the preemption provision standardizes the economic regulation of the trucking industry, leaving state safety regulation in place. The negligent-hiring is such a safety regulation and the regulation is "with respect to motor vehicles" as the FAAAA requiers. 
- Robinson argues that the negligent-hiring claims are preempted by the text and conflicts with the federal licensing scheme. Holding brokers liable for such state law claims would undermine the uniformity congress wanted from the FAAAA. 14501(c)(2)(a) applies only to the motor vehicles themselves, not the drivers or brokers. Allowing states to regulate under the pretext of safety would undermine the purpose of the FAAAA.
