#+title: February

* Havana Docks v Royal Carribean Cruises // https://www.scotusblog.com/cases/case-files/havana-docks-corporation-v-royal-caribbean-cruises-ltd/
- In 1905 Cuba made an agreement with Havana Docks. Havana Docks would build a pier and terminal building in Havana Harbor. In exchange Havana Docks would have rights to the harbor for some time. Ultimately Havana Docks built 3 piers and 3 terminal buildings that they would have rights to for 99 years. In 1960 (following the Cuban Revolution) Cuba expropriated the assets of Havana Docks. Cuba did not compesate Havana Docks "for the value of all works" as was required by their agreement. Havana Docks received a certified claim of $9.18 million in 1971 (with interest nearly $100m) at the Foreign Claims Settlement Commission. As part of the Helms-Burton act (1996) congress expanded sanctions on Cuba and allowed plaintiffs with a claim a private right of action against those trafficking in expropriated assets. Such claims remained unavailable while suspended by the president until 2019. Since 2015 Cruise lines have been bringing tourists to the expropriated docks. Havana Docks sued in District Court (S.D.Fl.) and won big! The Cruise lines then appealed to the 9th Circuit. The 9th circuit reversed finding that by the time the cruise lines trafficked in the expropriated assets (used the ports) Havana Dock's 99 years were up.
- Havana Docks argues that Helms-Burton grants a private right of action for any traficking of confiscated property. Their property was confiscated and the cruise lines trafficked in it. Once property is confiscated it remains confiscated and cannot be trafficked in until its rightful owner is compensated.
- The cruise lines argue that: They were liscenced by the government to travel to Cuba; The Cuban government wouldn't allow them to disembark except at the dock (the law has an exception for transactions which are "necessary to the conduct of [lawful] travel"); and that HDC's property interest had ended by the time the cruise liners used the docks. The cruise liners argue that the "trefficked proprety" is really Havana Dock's concession (their rights to make money from the docks) and not the docks themselves.

* Exxon Mobil v Corporacion Cimex, S.A. // https://www.scotusblog.com/cases/case-files/exxon-mobil-corp-v-corporacion-cimex-s-a/
- In the early 1900s Standard Oil (Now Exxon Mobil) did bussiness in Cuba. This involved building refineries, product terminals, and service stations. On June 29, 1960 the Cuban government expropriated this property and gave it to their state owned oil companies. The FCSC certified Exxon's claim for $71m (with interest now over $1b). Under the Helms-Burton act Exxon is suing Cimex (The Cuban SOE that was given their property). The Distrcit court found that defendants (instrumentatlities of a foreign sovereign) are entitled to foreign sovereign immunity, and that only one defendant fell within an exception and could be sued. On appeal the circuit court found that all the defendants were protected by foreign sovereign immunity.
- Exxon argues that the Helms-Burton act displaces the Foreign Sovereign Immunities Act. The Helms-Burton act "speak[s] clearly to withdraw sovereign immunity." The Helms-Burton act holds liable "any person that [...] traffics in property which was confiscated by the Cuban Government" and defines "person" to include "any agency or instrumentatlity of a foreign state" (22.6082, 22.6023).
- The point of the law is to let people sue over property confiscated by Cuba. Most of the property was taken in Cuba and given to SOEs. Requiring suits to also fall under an FSIA exception would stop most of the claims the law is inteded to allow. The law elsewhere refers to judgements against Cuban instrumentatlities. It then makes those judgements unenforcable against a transition government. 
- Cimex argues Helms-Burton act title 3 claims can only be brought against state instrumentatlities if they fall within an exception to Foreign Sovereign Immunity. Congress could have amended the FSIA as part of the act, as they've done with other acts and as they proposed to do before objections. Congress chose not to. Under Kirtz "immunity is not abrogated if any plausible interpretation of the statute would preserve it" (Brief for Resp.). The interpretation petitioners argue for is broad, it would waive immunity for any instrumentatlities, not just Cuban ones.

* Enbridge Energy, LP v Nessel // https://www.scotusblog.com/cases/case-files/enbridge-energy-lp-v-nessel/

* Pung v Isabella County, Michigan // https://www.scotusblog.com/cases/case-files/pung-v-isabella-county-michigan/

* US v Hemani // https://www.scotusblog.com/cases/case-files/united-states-v-hemani/

* Hunter v US // https://www.scotusblog.com/cases/case-files/hunter-v-united-states-2/

* Montgomery v Caribe Transport II // https://www.scotusblog.com/cases/case-files/montgomery-v-caribe-transport-ii-llc/
