#+title: February

* Havana Docks v Royal Carribean Cruises // https://www.scotusblog.com/cases/case-files/havana-docks-corporation-v-royal-caribbean-cruises-ltd/
- In 1905 Cuba made an agreement with Havana Docks. Havana Docks would build a pier and terminal building in Havana Harbor. In exchange Havana Docks would have rights to the harbor for some time. Ultimately Havana Docks built 3 piers and 3 terminal buildings that they would have rights to for 99 years. In 1960 (following the Cuban Revolution) Cuba expropriated the assets of Havana Docks. Cuba did not compesate Havana Docks "for the value of all works" as was required by their agreement. Havana Docks received a certified claim of $9.18 million in 1971 (with interest nearly $100m) at the Foreign Claims Settlement Commission. As part of the LIBERTAD act (1996) congress expanded sanctions on Cuba and allowed plaintiffs with a claim a private right of action against those trafficking in expropriated assets. Such claims remained unavailable while suspended by the president until 2019. Since 2015 Cruise lines have been bringing tourists to the expropriated docks. Havana Docks sued in District Court (S.D.Fl.) and won big! The Cruise lines then appealed to the 9th Circuit. The 9th circuit reversed finding that by the time the cruise lines trafficked in the expropriated assets (used the ports) Havana Dock's 99 years were up.
- Havana Docks argues that LIBERTAD grants a private right of action for any traficking of confiscated property. Their property was confiscated and the cruise lines trafficked in it. Once property is confiscated it remains confiscated and cannot be trafficked in until its rightful owner is compensated.
- The cruise lines argue that: They were liscenced by the government to travel to Cuba; The Cuban government wouldn't allow them to disembark except at the dock (the law has an exception for transactions which are "necessary to the conduct of [lawful] travel"); and that HDC's property interest had ended by the time the cruise liners used the docks. The cruise liners argue that the "trefficked proprety" is really Havana Dock's concession (their rights to make money from the docks) and not the docks themselves.

* Exxon Mobil v Corporacion Cimex, S.A. // https://www.scotusblog.com/cases/case-files/exxon-mobil-corp-v-corporacion-cimex-s-a/

* Enbridge Energy, LP v Nessel // https://www.scotusblog.com/cases/case-files/enbridge-energy-lp-v-nessel/

* Pung v Isabella County, Michigan // https://www.scotusblog.com/cases/case-files/pung-v-isabella-county-michigan/

* US v Hemani // https://www.scotusblog.com/cases/case-files/united-states-v-hemani/

* Hunter v US // https://www.scotusblog.com/cases/case-files/hunter-v-united-states-2/

* Montgomery v Caribe Transport II // https://www.scotusblog.com/cases/case-files/montgomery-v-caribe-transport-ii-llc/
