#+title: January

* Chevron v Plaquemines Parish, La. // https://www.scotusblog.com/cases/case-files/chevron-usa-inc-v-plaquemines-parish-louisiana-2/
- Local Governments in Louisiana accuse oil and gas companies (Chevron) of operating along the Louisiana Coast without a permit or in violation of the terms of their permit. The oil and gas companies moved to have the case removed to federal court. Federal law allows US officers (or any person acting under that officer) to have civil cases removed to federal court. The 5th circuit found that while they were acting under a US officer for purposes of the statue they could not remove this case because the contract for aviation fuel was not related enough to the crude oil production on the Louisiana coast.
- Chevron argues that they were acting under and officer of the US because the operators along the Louisiana coast were federal contractors at the time. They argue that the crude oil production was related to the aviation fuel production--the refined aviaton fuel cannot be produced without crude oil. Congress amended the statue in 2011 from "for any act under color of such office" to "for or relating to any act under color of such office".
- The SG agrees with Chevron and adds that During WWII (The time of the contract) the oil industry operated closely with the Petroleum Administration for War (PAW). That special war-time relationship supports the removal to federal court.
- Plaquemines Parish argues that the contract did not direct the oil and gas companies to produce crude oil. The federal contracts were related to the refineries and cannot extend to crude production. They actually point to the PAW as controlling the allocation of crude oil. Because the PAW controlled the allocation of crude oil the refineries would have gotten it reguardless of the companies crude oil production.
- Alito recused for financial interest in a party to lower court litigation. // https://www.supremecourt.gov/DocketPDF/24/24-813/391167/20260108162001341_Letter%20from%20Clerk%20in%20No.%2024-813.pdf

* Little v. Hecox // https://www.scotusblog.com/cases/case-files/little-v-hecox/
- In 2020 Idaho (Bradley Little is the Governor of Idaho) passed HB500, a law banning transgender women and girls from school sports for women and girls. Lindsey Hecox is a transgender woman who wants to participate in track and cross-country at Boise State University. Hecox went to district court to challenge the law, arguing that it violates the equal protection clause. The District court granted a preliminary injunction barring enforcement of the law. The 9th Circuit upheld the preliminary injunction. Idaho appealed that decision to SCOTUS. After years of litigation Hecox decided to stop participating in sports and so moved to have her case dismissed as moot. SCOTUS deferred consideration of mootness pending oral argument.
- Hecox argues that the case is not ripe. Hecox is no longer playing women's sports and has committed to not challenge this law ever again. Hecox also argues that any argument related to competative advantage should be remanded to the lower court. Idaho wants to challenge the factual determinations of district court which should be initially developed a trial below.
- On the merits Hecox argues that HB500 triggers heightened scrutiny and is unconstitutional under the equal protection clause. Transgender people are a quasi-suspect class because they have faced a history of de facto and de jure discrimination: laws regulating gender deviance and impersonating females. HB500 also discriminates on the basis of sex in violation of Title IX. HB500 fails heightened scrutiny because it is overinclusive, banning even trans women who have lower circulating levels of testosterone than cis women.
- Idaho argues that the act is permissible sex discrimination. Hecox does not challenge sex based classifications but the definition of sex described in HB500 (birth sex). The 14th amendment uses sex as an individual's role in reproduction, not the modern sense of gender identity. The law does not discriminate based on transgender status because it determines sex and discriminates only on that basis: men can only compete on men's teams and women can only compete on women's teams, regaurdless of gender identity. Trans people are not a quasisuspect class (see Barrett's concurence in Skrmetti).
- I think the procedural arguments here are quite compelling even if they are suspicious. It would benefit from a more developed record which isn't happening in this case. I also think it's likely that the justices know what they want the law to look like and will use this opportunity.
** OA // https://www.supremecourt.gov/oral_arguments/argument_transcripts/2025/24-38_n75p.pdf
- Kagan is interested in the implications for as-applied challenges
- Gorsuch is the only one interested in the quasi-suspect class discussion
  

* West Virginia v. BPJ // https://www.scotusblog.com/cases/case-files/west-virginia-v-b-p-j-2-2/
- In 2021 West Virginia passed the Save Women's Sports Act barring the transgender women and girls from participating in women's and girl's sports teams in public secondary schools and colleges. BPJ (age 15) is a high school student who wants to compete in girls' track and field. BPJ sought and received received a preliminary injunction from district court enjoining enforcement of the law against her.
- BPJ's brief spends a comical amount of time describing how bad she is: placing 54th/55, 64th/65, "coach said she was too slow to compete in running". But she had a lot of fun! Are you really going to be mean to this poor 15 year old >:( ? BPJ also makes all the same arguments Hecox makes.
- Blah blah blah, it's the same picture. Maybe they granted cert here in case Little v Hecox gets mooted?

* Galette v. New Jersey Transit Corporation // https://www.scotusblog.com/cases/case-files/galette-v-new-jersey-transit-corporation/
- consilidated with New Jersey Transit Corporation v. Colt // https://www.scotusblog.com/cases/case-files/new-jersey-transit-corporation-v-colt/
- Galette was a passenger in a car hit by a New Jersey Transit bus in Pennsylvania. Galette sued New Jersey in Pennsylvania court. New Jersey Transit moved to have the case dismissed on the grounds that they're an arm of New Jersey. One state can't be sued in the court of another state under interstate sovereign immunity. The Supreme Court of Pennsylvania agreed with New Jersey Transit and dismissed the case.
- Jeffery Colt was hit by a New Jersey Transit bus in a crosswalk in New York. Colt sued New Jersey Transit in New York court. New Jersey Transit moved to have the case dismissed on the grounds that they're an arm of New Jersey. One state can't be sued in the court of another state under interstate sovereign immunity. The New York Court of Appeals (The highest court in New York) disagreed with New Jersey Transit and declined to dismiss the case.
- New Jersey Transit argues that they're an arm of New Jersey. They were created by statute. The statue refers to them as an "instrumentality" of the state. The statute gives them general law enforcement powers, eminent domain powers, and regulatory authority. The governor can appoint and remove it's board members. The governor can  veto actions the board takes. They depend on the state for capital and operating costs. The statute even has waivers of sovereign immunity.
- Galette and Colt argue that New Jersey Transit should not get interstate sovereign immunity. New Jersey Transit can bring its own cases and is exclusively liable for judgements against it. It enters in it's own contracts that it, not New Jersey, is responsible for. It hires its own employees and contractors and acquires and disposes of its own property. It generates its own revenue. It operates outside the state, competing with private enterprise.
- Galette and Colt also argue that interstate sovereignty shouldn't apply because someone operating in another state should be able to be held liable by that state's citizens in that state's courts. It's outrageous that you can run over a New Yorker in New York and New York courts are powerless to hear the case.
- New Jersey Transit seems like an arm of New Jersey to me. All of these things, except operating outside of the state, seem to describe other government-created entities just fine. I have no priors on interstate immunity so I have no prediction.

* Wolford v. Lopez // https://www.scotusblog.com/cases/case-files/wolford-v-lopez/
- Hawai'i (Anne Lopez is the AG of Hawai'i) passed a law that requires people to obtain consent before bringing a gun to various places including private property. A group of gun owners (Jason Wolford owns a gun) want to carry their guns so they challenged the law for violating the 2nd amendment. The district court preliminarily enjoined most of the law, the circuit court narrowed that ruling, but still enjoins it as it applies to private property. Plaintiff now appeal to SCOTUS.
- Hawai'i argues that this does not implicate the 2nd amendment because at the time of enactment there was no right to enter private property armed. While you may have an implied liscense to enter private property that need not extend to allowing armed entry. Hawai'i goes on to argue that the law is permissible under Bruen. Hawai'i points to laws requiring consent to enter armed "inclosed" or "improved" property.
- Plaintiffs argue that the law violates the 2nd amendment under Bruen. This law makes it presumptively criminal to carry guns almost anywhere in the state even with a permit. This is no different from the unconstitutionally restrictive permitting regieme from Bruen. Plaintiffs also object to the colonial laws. One law was intended to keep hunters from hunting on private land closed to entry. The other law was intended to deny former slaves gun rights. Bad law! Go to your room!
- It is quite strange that a legislature can mark specific places gun free, but not certain classes of place. It would also be strange if the legislature could just mark the whole state gun free and switching to opt-in would be pretty much that. The colonial laws aren't very compelling. I predict Hawai'i loses, but I'm also wondering what happens with the rest of the law.

* M&K Employee Solutions v Trustees of the IAM National Pention Fund // https://www.scotusblog.com/cases/case-files/m-k-employee-solutions-llc-v-trustees-of-the-iam-national-pension-fund/
- M&K wants to leave their multiemployer pention fund, IAM National Pention Fund. The Multiemployer Pention Plan Amendments Act of *1980* (how did we make it this long?) requires employers to make a one-time payment when they leave a multiemployer pention fund. This fee keeps employers from leaving the fund at the first sign of trouble and starting a snowball. The MPPAA requires an actuarial to calculate the fee based on the fund's shortfall on the last day of the previous year (%Y-1/12/31). The question is do we use the calculation the actuarial made on that date? Or can the fund revise the shortfall as of that date based on changing assumptions or strategies.
- The fund wants the actuarial to use the current assumptions. That is simply the best determination of a fee that will make up the shortfall in the fund. The actuary must do their best, so they must use the currently (as of calculation) assumptions.
- M&K argues that the actuarial must calculate the fee "as of" the withdrawal date means using the shortfall as it was calculated on that date. Also funds could try to change to more pessimistic actuarials who would calculate higher fees. (Why wouldn't they do this anyway? Also it seems like that's what they did lol.)
- The statute seems to side with the fund but I give myself <50% confidence that I understand what it's saying. It does seem better for bussinessess if they know in advance what their withdrawl fee will be, but that's a policy argument. Also how did this take so long? was it covid? Also It's late, I'm tired.

* Trump v Cook // https://www.scotusblog.com/cases/case-files/trump-v-cook-2/
- In 2024 Trump purported to fire Lisa Cook from the FED Board of Governors. FED Governors can only be removed for cause under the Federal Reserve Act. Trump alledges that Lisa Cook lied on her mortgage applications in 2021. She probably did not lie on her mortgage applications. Regaurdless, Trump concluded that this "calls into question [Cook's] competence and trustworthiness as a financial regulator". Cook sued to stop the firing and the DC District court granted a preliminary injunction stopping the administration from firing her. Trump appealed to the DC Circuit court which upheld, and now appeals to SCOTUS.
- Cook argues that she must have standing. For cause removal protection is meaningless if there is no process and one cannot appeal to the judiciary.
- Cook then argues that Trump's basis is insufficient. The FRA's for cause removal protection should be read as incorporating the same protections as other executive officials: "inefficiency, neglect, malfeasance (INM) in office, or ineligibility". Trump's allegations do not meet that statndard. Cook argues that she's entitled to notice and a hearing (Shurtleff v US, in which a senate confirmed officer was entitled to notice and a hearing; Reagan v US, in which an inferior officer was not). Cook also argues that the FED is very special! and important!
- Trump argues that the Cook is not entitled to notice and a hearing. The law says nothing about notice and a hearing and congress knows how to write those words. Also you can't sue over your holding public office because it's not your property; you don't get due process rights when we take it away.
- Trump then argues that the mortgage fraud allegations were sufficient. Trump argues for a different standard: causes for removal must be "related to their conduct, ability, fitness, or competence". Which the mortgage fraud allegation is. If Congress wanted the INM standard they could have said so. If Congress wanted notice and a hearing they could have said so. Trump also argues that the remedy of reinstatement is unlawful. The Civil Service Reform Act allows reinstatement for officers and employees but explicitly excludes Senate-Confirmed officers like Cook. And the court can't use equitable powers because the office is not property.
- There's a lot of bad text here. Congress should have written more process for the FED. But the FED is special! And it really wouldn't make sense for a member of the FED to be removed by the executive with no process and no judicial remedy. Notably I don't see any argument about the FED wielding executive powers. In either direction! Cook doesn't even use the phrase "executive power" except in a footnote quoting Trump's brief quoting Wilcox, which was *all about* executive power! What am I missing here?
- I think based on recent precedent Trump wins. But based on Robert's order in Wilcox and the disposition of Kagan's dissent I have to predict they're going to make some new law for Cook to win.
