#+title: January

* Chevron v Plaquemines Parish, La. // https://www.scotusblog.com/cases/case-files/chevron-usa-inc-v-plaquemines-parish-louisiana-2/
- Local Governments in Louisiana accuse oil and gas companies (Chevron) of operating along the Louisiana Coast without a permit or in violation of the terms of their permit. The oil and gas companies moved to have the case removed to federal court. Federal law allows US officers (or any person acting under that officer) to have civil cases removed to federal court. The 5th circuit found that while they were acting under a US officer for purposes of the statue they could not remove this case because the contract for aviation fuel was not related enought to the crude oil production on the Louisiana coast.
- Chevron argues that they were acting under and officer of the US because the operators along the Louisiana coast were federal contractors at the time. They argue that the crude oil production was related to the aviation fuel production--the refined aviaton fuel cannot be produced without crude oil. Congress amended the statue in 2011 from "for any act under color of such office" to "for or relating to any act under color of such office".
- The SG agrees with Chevron and adds that During WWII (The time of the contract) the oil industry operated closely with the Petroleum Administration for War (PAW). That special war-time relationship supports the removal to federal court.
- Plaquemines Parish argues that the contract did not direct the oil and gas companies to produce crude oil. The federal contracts were related to the refineries and cannot extend to crude production. They actually point to the PAW as controlling the allocation of crude oil. Because the PAW controlled the allocation of crude oil the refineries would have gotten it reguardless of the companies crude oil production.
- Alito recused for financial interest in a party to lower court litigation. // https://www.supremecourt.gov/DocketPDF/24/24-813/391167/20260108162001341_Letter%20from%20Clerk%20in%20No.%2024-813.pdf

* Little v. Hecox // https://www.scotusblog.com/cases/case-files/little-v-hecox/

* Trump v Cook //
