#+title: March

* Watson v Republican National Committee // https://www.scotusblog.com/cases/case-files/watson-v-republican-national-committee/
- Mississippi (Michael Watson is the Secretary of State of Mississippi) law allows election ballots to be recieved up to five days after election day and still be counted. The RNC don't like that one bit. The RNC went to the S.D.MS to challenge the law. The District Court upheld the law. The 5th circuit then reversed and denied an en banc rehearing. Now Mississippi is asking SCOTUS to reverse the 5th circuit.
- Mississippi argues that election day is the day voters make their choice. The voter chooses by casting his ballot, not by his ballot being received. Congress may set a ballot-receipt deadline, but they did not do so in the election day statutes. Most states allow post-election receipt. States allowed post-election receipt for 165 years.
- The RNC argues that election day is "the day by which ballots must be both cast by voters and received by state officials." Mail ballots cannot be "final" before they are received because the sender can recall the mail for a time. Historical laws allowing for post-election receipt of ballots are rare and short-lived. Laws which effectively consumate the election before election day conflict with federal statute(Foster v Love); post-election receipt effectively consumates the election after election day. Federal law doesn't authorize post-election receipt even when providing for absentee voting.

* Keathley v Buddy Ayers Construction // https://www.scotusblog.com/cases/case-files/keathley-v-buddy-ayers-construction-inc/

* Noem v Al Otro Lando // https://www.scotusblog.com/cases/case-files/noem-v-al-otro-lado/
- In response to increased arrivals from Mexico, DHS adopted a policy of metering at southern ports of entry. Metering means turning arrivals away when they arrive at the Mexico side of a port of entry. In 2016 DHS used metering to prevent arrivals without valid travel documents based on operational requirements. After November 2016 the Trump administration expanded metering to all ports. In 2018 a memorandum directed CBP to meter when appropriate to ensure security, safety, sanitation, and orderly processing. In 2020 an OIG report found that ports operated below capacity while turning away migrants for inappropirate reasons. DHS is not currently directed to meter port but maintains that metering is lawful.
- 1158(a)(1) "Any alien who is physically present in the United States or who arrives in the United States [...] may apply for asylum[.]"
- 1225(a) "An alien [...] who arrives in the United States shall be deemed for purposes of this chapter an applicant for admission." 
- In 2017 Al Otro Lando (an immigration rights organization) brought a class action to challenge metering. The district court (S.D.Ca.) certified a class of noncitizens who want to seek asylum at a port of entry. The district court then ruled against metering. The government appealed to the 9th circuit which affirmed ruling. Now the government is appealing to SCOTUS.
- The government argues that "an alien stopped in Mexico is not entitled to apply for asylum". 1158(a)(1) does not include people stopped in Mexico. The presumption against extraterritoriality weighs against applying this law to aliens in Mexico. Sale upheld the interdiction of Haitians at sea under the presumption against extraterritoriality. The ruling below undermines the Executive's ability to manage a safe and orderly border.
- Respondent argues that DHS cannot evade their duty to accept asylum applications by stopping immigrants in Mexico. In 1158(a)(1): If an alien "who arrives in the US" must be across the border then it merely repeats part of the previous group of aliens "physically present in the US"--the suplusage canon demands a different interpretation. Metering incentivises aliens to cross the border surreptitiously (so that they are "physically present")--this is contrary to the purpose of the IIRIRA. Turning back aliens in this way is refoulment, which violates the 1967 Protocol relating to the Status of Refugees. Metering is a departure from historical practice.

* Flower Foods v Brock // https://www.scotusblog.com/cases/case-files/flower-foods-inc-v-brock/

* Abouammo v United States // https://www.scotusblog.com/cases/case-files/abouammo-v-united-states/

* Jules v Andre Balazs Properties // https://www.scotusblog.com/cases/case-files/jules-v-andre-balazs-properties/

* Pitchford v Cain // https://www.scotusblog.com/cases/case-files/pitchford-v-cain/

* Trump v Barbara // https://www.scotusblog.com/cases/case-files/trump-v-barbara/

