#+title: March

* Watson v Republican National Committee // https://www.scotusblog.com/cases/case-files/watson-v-republican-national-committee/
- Mississippi (Michael Watson is the Secretary of State of Mississippi) law allows election ballots to be recieved up to five days after election day and still be counted. The RNC don't like that one bit. The RNC went to the S.D.Mi. to challenge the law. The District Court upheld the law. The 5th circuit then reversed and denied an en banc rehearing. Now Mississippi is asking SCOTUS to reverse the 5th circuit.
- Mississippi argues that election day is the day voters make their choice. The voter chooses by casting his ballot, not by his ballot being received. Congress may set a ballot-receipt deadline, but they did not do so in the election day statutes. Most states allow post-election receipt. States have allowed post-election receipt for 165 years.
- The RNC argues that election day is "the day by which ballots must be both cast by voters and received by state officials." Mail ballots cannot be "final" before they are received because the sender can recall the mail for a time. Historical laws allowing for post-election receipt of ballots are rare and short-lived. Laws which effectively consumate the election before election day conflict with federal statute(Foster v Love); post-election receipt effectively consumates the election after election day. Federal law doesn't authorize post-election receipt even when providing for absentee voting.
** OA
- Mississippi claims that mail ballots cannot be recalled. The text seems unclear.

* Keathley v Buddy Ayers Construction // https://www.scotusblog.com/cases/case-files/keathley-v-buddy-ayers-construction-inc/
- In 2019 Thomas Keathley filed for chapter 13 bankruptcy. A chapter 13 bankruptcy estate includes assets acquired after filing. The filer must update the court as he acquires such assets. In August 2021 David Fowler (an employee of Buddy Ayers Construction) crashed his car into Keathley's, causing serious injury. And giving him an asset--a personal injury claim against Buddy Ayers Construction. Keathley filed the personal injury suit in December 2021. Ayers pointed out that Keathley never told the bankruptcy court about this claim. Keathley had told his lawyer but did not update his schedule of assets until after Ayers made this argument. Ayers argues that the claim is therefore barred under the doctrine of judicial estoppel. The district court (E.D. Ar.) agreed and dismissed the case as Ayers wanted. The 5th circuit affirmed, reasoning that the non-disclosure was intentional (it didn't get lost in the mail or something) and had a potential benefit to him (the bankruptcy estate could've demanded the money sooner out of his claim). Now he appeals to SCOTUS.
- Keathley argues that the 5th circuit's rule is overly harsh and inflexible. Equitable rules, like judicial estoppel, should allow judges to weigh factors--here the motive to conceal assets against evidence of his intent (reliance on council, prompt correction, bankruptcy court findings). Judicial estoppel exists to discourage misleading the court, the 5th circuit's rule estops accidental conduct which does not serve that purpose. The ruling benefits the wrongdoer and punishes the victim and creditors, that does not serve the principles of equity. 
- Ayers argues that Keathley represented to the bankruptcy court that he had no claim so he cannot pursue his claim here. Those are contradictory positions so judicial estoppel prevents him from doing so. Judicial estoppel requires three elements: (1) the party must take clearly inconsistant positions, (2) the party must persuade a court to accept the earlier position, and (3) the party would derive and unfair advantage from the inconsistant position. (1) Keathly represented that he had no claim and is now persuing a claim, (2) Keathley persuaded to the court that no claim existed and confirmed a payment plan that account for it, (3) Keathley benefitted by persuing a claim without alerting his creditors. 13 bankruptcy has time limits which make it impractical for debtors to amend the repayment plan after late disclosure. Allowing parties to amend their representations after being caught creates a perverse incentive.

* Noem v Al Otro Lando // https://www.scotusblog.com/cases/case-files/noem-v-al-otro-lado/
- In response to increased arrivals from Mexico, DHS adopted a policy of metering at southern ports of entry. Metering means turning arrivals away when they arrive at the Mexico side of a port of entry. In 2016 DHS used metering to prevent arrivals without valid travel documents based on operational requirements. After November 2016 the Trump administration expanded metering to all ports. In 2018 a memorandum directed CBP to meter when appropriate to ensure security, safety, sanitation, and orderly processing. In 2020 an OIG report found that ports operated below capacity while turning away migrants for inappropirate reasons. DHS is not currently directed to meter port but maintains that metering is lawful.
- 1158(a)(1) "Any alien who is physically present in the United States or who arrives in the United States [...] may apply for asylum[.]"
- 1225(a) "An alien [...] who arrives in the United States shall be deemed for purposes of this chapter an applicant for admission." 
- In 2017 Al Otro Lando (an immigration rights organization) brought a class action to challenge metering. The district court (S.D.Ca.) certified a class of noncitizens who want to seek asylum at a port of entry. The district court then ruled against metering. The government appealed to the 9th circuit which affirmed ruling. Now the government is appealing to SCOTUS.
- The government argues that "an alien stopped in Mexico is not entitled to apply for asylum". 1158(a)(1) does not include people stopped in Mexico. The presumption against extraterritoriality weighs against applying this law to aliens in Mexico. Sale upheld the interdiction of Haitians at sea under the presumption against extraterritoriality. The ruling below undermines the Executive's ability to manage a safe and orderly border.
- Respondent argues that DHS cannot evade their duty to accept asylum applications by stopping immigrants in Mexico. In 1158(a)(1): If an alien "who arrives in the US" must be across the border then it merely repeats part of the previous group of aliens "physically present in the US"--the suplusage canon demands a different interpretation. Metering incentivises aliens to cross the border surreptitiously (so that they are "physically present")--this is contrary to the purpose of the IIRIRA. Turning back aliens in this way is refoulment, which violates the 1967 Protocol relating to the Status of Refugees. Metering is a departure from historical practice.

* Flowers Foods v Brock // https://www.scotusblog.com/cases/case-files/flower-foods-inc-v-brock/
- Flowers Foods sells baked goods to independent distributors. The independent distributors then distribute Flowers products to retail stores (supermarkets, drugstores, convenience stores). Brock (an independent distributor) has a distribution agreement with Flowers which requires arbitration for all disputes. Brock brought a class action in district court and Flowers moved to dismiss or stay to resolve the dispute in arbitration. The district court denied the motion, reasoning that transportation workers "engaged in foreign or interstate commerce" are excempt from the Federal Arbitration Act. (Brock doesn't cross state lines, his territory is entirely within Colorado.) Flowers appealed and the 10th cir. affirmed. Now Flowers is appealing to SCOTUS.
- 9 USC Section 1: "nothing herein contained shall apply to contracts of employment of seamen, railroad employees, or any other class of workers engaged in foreign or interstate commerce."
- Flowers argues that drivers like Brock are not engaged in interstate commerce. Brock does not have any direct, active, or necessary role in interstate commerce. Brock receives the products in Colorado and drives them to stores in Colorado. The 10th cir. errd in focusing on the underlying transaction (Flowers to retailers). The correct analysis is focused on Brocks work which is entirely intrastate. The FAA is intended to make motions to compel arbitration quick and inexpensive, the 10th circuit's rule requires extensive discovery and "prolonged mini trials."
- Brock argues that he is a "last-mile driver" whose work transports goods along the last leg of an interstate journey. Last-mile drivers, like railworkers who remain in one state, are "engaged in intersate commerce" under the text and precedent of Section 1. The question here is not complicated and does not require extensive discovery.

* Abouammo v United States // https://www.scotusblog.com/cases/case-files/abouammo-v-united-states/

* Jules v Andre Balazs Properties // https://www.scotusblog.com/cases/case-files/jules-v-andre-balazs-properties/

* Pitchford v Cain // https://www.scotusblog.com/cases/case-files/pitchford-v-cain/

* Trump v Barbara // https://www.scotusblog.com/cases/case-files/trump-v-barbara/

