#+title: November

* Rico v US // https://www.scotusblog.com/2025/10/fugitive-tolling-and-federal-supervised-release/
- Rico pleaded was sentenced to 84 months in prison and 48 months supervied release for conspiring to distribute methamphetamine. During supervised release she absconded and used methamphetamine. That's against the terms of her supervised release. The judge revoked her supervised release, and ordered her back to prison for 2 months followed by more supervised release. During this supervised release she absconded and used methamphetamine and did more crimes. The judge ordered 16 months of prison and 24 months of supervised release.
- If a criminal escapes prison their sentence stops running; this is fugitive-tolling. Rico says she deserved credit for her time under supervised release because fugitive-tolling doesn't apply to supervised release. Supervised realease is governed by statute and the statute says nothing about the common-law practice of fugitive-tolling. The government says, fugitive-tolling does apply to supervised release. Fugitive-tolling is a good idea and it'd be dumb if criminals could avoid parts of their sentence by noncomplicance.
- Rico's behavior was particularly bad here. She didn't just miss a meeting or relapse. The government doesn't argue that such minor errors would trigger fugitive-tolling, which is a pretty decent deal.
- lgtm. Probably government wins.

* Hencely v Fluor Corp. // https://www.scotusblog.com/2025/10/court-to-consider-protection-of-military-contractors-from-certain-suits/
- Hencely was a soldier stationed a Bagram Airfield. Fluor Corp. was contracted by the US government to perform work at Bagram Airfield. Fluor Corp. Hired Ahmad Nayeb for the night shift with responsibilities not including blowing anyone up in a suicide bombing. On November 12, 2016 Nayeb detonated an explosive vest, "killing himself and five others and severely wounding seventeen more, including Hencely".
- Hencely wants to sue Fluor Corp. because blowing up twenty two soldiers probably violates Fluor's military contract, and also their entrustment and lack of supervision was negligent under state law. Fluor Allowed Nayeb to smuggle explosives into his work, use their provided tools to construct the explosive vest, and failed to escort him off base at the end of his shift as they routinely do.
- The military encouraged contractors to hire locals under the "Afghan First" program. The military knew Nayeb was former Taliban but sponsored him anyway believing he had broken ties. The military was warned of an attack the day of. The military did not share any of this intelligence with Fluor.
- The district court found, and the circuit court agreed, that Hencely is not a third-party beneficiary of the contract and so can't sue for its breach (No word on whether suicide bombings are a violation of said contract). They also agreed that any tort claim was not allowed by the Federal Tort Claims Act under the combatant activities exception.
- Boyle v United Tech. found that state-law design-defect claims could not be brought against the manufacturer of a military helicopter. The courts below rely on this reasoning that the combatant activities exception shields contractors (as well as the military) from state-law claims.
- Ronald Mann at scotus blog expects the Boyle will be overturned, "Boyle’s relatively unmoored approach is an outlier in the court’s modern jurisprudence [...] I would not be all that surprised if the court ends up overruling Boyle." The text of the combatant activities exception reads "The provisions of this chapter [...] shall not apply to [...] Any claim arising out of the combatant activities of the military or naval forces, or the Coast Guard, during time of war." That text does not include the word "contractor" which seems important.

* Coney Island Auto Parts v Burton // https://www.scotusblog.com/2025/10/is-there-a-time-limit-on-vacating-a-void-judgment/
- Vista-Pro Automotive (Burton) was going through bankruptcy and in related proceedings sued Coney Island Auto Parts for unpaid invoices. Coney Island Auto Parts didn't respond to the complaint and so Burton was awarded a default judgement. Burton tried to collect on that judgement for 5 years. Burton got a hold placed on their bank account in New York and then Coney Island Auto Parts challenged the judgement. New York kicked them back to Tennessee and Tennessee said the motion wasn't timely... it *has* been 7 years.
- frcp 60(c)(1) "A motion under Rule 60(b) must be made within a reasonable time".
- Coney Island Auto Parts is asking for no time limit on challenging its judgement. "Coney Island also contends that it would not sow chaos to grant defendants an unlimited amount of time to challenge judgments as void." They also claim that this is the rule adopted by most circuits. And this would only take effect if the judgement is void. Do you *want* bad judgements to be enforced? huh?
- Burton argues that the rules say what they say; seven years is unreasonable; all sorts of statutes have time limits; and time limits are good for speed and finality.
- If I had more time I'd read why (if?) other circuits have no time limit. That seems unreasonable. Time limits are good! Pay up!
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-808_lkgn.pdf
- Alito, writing for a unanimous court, holds that the reasonable time requirement applies to this rule 60(b) motion. Rule 60(c)(1) requires that rule 60(b) motions "must be made within a reasonable time". A motion for releif from a void judgement is a rule 60(b) motion. Motions for the releif from a void judgement must be made within a reasonable time. QED.
- Alito agrees that "several Courts of Appeals, and a prominent treatise" found otherwise. "These authorities acknowledge that their interpretation clashes with Rule 60’s text." The clash is over; the text won.
- Alito finally finds that any Due Process or historical practice complaints cannot carry an alternative finding. When the text is clear interpretive tools cannot weigh on the meaning.
- Sotomayor in a concurance disagrees with making any finding related to the Due Process clause.

* The Hain Celestial Group v Palmquist // https://www.scotusblog.com/2025/10/justices-to-consider-diversity-jurisdiction-procedural-problems-and-baby-food/
- Palmquist claims the baby food she bought was tainted with heavy metals. She sued Whole Foods (The retailer) and The Hain Celestial Group (The manufacturer). Palmquist and Whole Foods are based in Texas and Hain isn't so Hain moved to remove the case to federal court under diversity jurisdiction. The federal judge dismissed the claim against Whole Foods and they had a trial. Palmquist won and now wants to appeal the dismissal against Whole Foods. Whole Foods argues that if they were part of the case then it shouldn't be removed to federal court because they're from Texas so if they want to sue they need a new trial in state court.
- Whole Foods was still in the case when they were in federal court moving for dismissal. Why didn't they make the argument then? Also, more trials? no! we already had a perfectly good trial. No one wants more trials, do your recreational litigation on your own time.

* VOS Selections v. Trump // https://storage.courtlistener.com/recap/gov.uscourts.cafc.23105/gov.uscourts.cafc.23105.159.0_1.pdf
- Goldsmith // https://www.execfunctions.org/p/the-tariff-case-and-the-major-questions
- Unikowsky // https://adamunikowsky.substack.com/p/balls-and-strikes
- Consolidated with Learning resources v Trump // https://www.scotusblog.com/cases/case-files/learning-resources-inc-v-trump/
- Jan-Feb: Trump imposed tariffs on Canada, China, and Mexico citing the National Emergencies Act (NEA) and The International Emergency Economic Powers Act (IEEPA).
- A number of bussinesses and states sued in the Court of International Trade claiming that the President exceeded his authority under IEEPA. A panel at The CIT agreed and ruled in favor of the plaintiffs in summary judgement.
- IEEPA allows the president to "regulate ... imporatation ... involving any property in which any foreign country or national thereof has any interest ..." . (https://uscode.house.gov/view.xhtml?req=(title:50%20section:1702%20edition:prelim)) That's broad language! It doesn't say the words "tariff" or "tax" or synonym though. So does "regulate" encompass "tariff"?
- The precursor to the CIT said the precursor to IEEPA empowered the president to make tariffs, and they had largely the same language.
- Respondants argue that even if "regulate" plausibly includes "tariff" that should be read out under the MQD. This is clearly a power of great economic signifigance and this is exactly the kind of general grant of authority that the MQD seeks to reign in. If congress wants the president to pass sweeping tariffs then they need to state it clearly. On the other hand, a federal court has already ruled that the president can tariff imports based on similar statutory langauge. If it didn't implicate the MQD then then why now?
- Also this is foreign policy; go mind your own business judiciary!
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-1287_4gcj.pdf
- Roberts, writing for the majority, finds that IEEPA does not authorize the President to impose tariffs. The government requires a large grant of power. It wants to impose tariffs worth (according to them) trillions of dollars, across every country in the world, based on unreviewable declarations of emergency. Other statutes granting presidential tarriff power are more specific and circumscribed. The MQD can't allow such a broad reading of this statute's language. That this power is in the context of an emergency does not affect the MQD. That this is in the context of foreign affairs does not affect the MQD.
- The word "regulate" in IEEPA does not grant the power tariff. Interpretting it that broadly would leave the long list of powers other (investigate, direct, compel, nullify, void, prevent or prohibit, etc.) meaningless. Also a tariff is a tax and other statutes that allow the executive to regulate clearly do not allow them to tax. When congress does grant the power to tax it does so clearly. Yoshida granted a much smaller power than the government needs here, it was a different (more constraining) statute, and it was a specialized court. It would be wrong to read IEEPA as codifying the findings in Yoshida.
- Kagan, in a concurance joined by Sotomayor and Jackson, takes issue with the MQD and its application here. A tax isn't a regulation. When congress grants the power to tax it uses terms like "duty," "tariff," or "surcharge." Reading the word "regulate" to be so expansive does not make sense in the statute and does not fit the pattern of statutes that do grant the power to levy taxes. This case is best decided through ordinary statutory construction; leave the MQD in the drawer.
- Kavanaugh, in a dissent joined by Thomas and Alito, argues that a tariff fits the ordinary understanding of "regulate" in the context of trade, and that the MQD is inapplicable. Kavanaugh points to the understanding of the founders that the power to regulate foreign commerce includes the power to tariff. The court has found taxing to be  part of congress's power to regulate commerce independent of its power to tax. Kavanaugh also reads IEEPA as codifying Yoshida because it was known to congress at the time it passed IEEPA and used the same language. Similarly Algonquin found that a statute with different language ("adjust the imports") were upheld as supporting a tariff power. The MQD also shouldn't apply in foreign affairs where we expect congress to use vague language to grant broad powers.

* Landor v Louisiana Dept. of Corrections and Public Safety // https://www.scotusblog.com/2025/11/court-to-consider-prison-inmates-religious-liberty-claims/
- Landor was serving a 5 month prison sentence. Landor grew a beard as part of his religious practice. Landor was transfered to Raymond Laborde correctional center. During intake Landor was forcibly shaved. Landor brought suit under RLUIPA (Religious Land Use and Institutionalized Persons Act). The district court found, and the 5th circuit upheld, that "RLUIPA does not allow private individuals to bring such claims seeking money damages."
- Landor argues that This interpretation leaves him without any relief. This allows prisons to deny Jewish inmates Kosher meals or Muslims halal. RFRA (The fed prison statute with the same language) authorizes money damages against prison officials.
- Louisiana argues that the statute cannot support damages against employees. The federal hook into state prison behavior is federal funds. Because the feds give the prison money they can stipulate those funds on some policies. The prison guards don't recieve the federal funds so they can't be the target of suit.
