#+title: October

* Villarreal v. Texas // https://www.scotusblog.com/cases/case-files/villarreal-v-texas/
- Villarreal was on trial for murder in Texas. During his testimony the court ran out of time and decided to recesss and continue Villarreal's testimony the next day. The Judge instructed the lawyers to avoid confering with Villarreal about his testimony and tried to walk the line by assuring Villareal he could talk with his lawyers about other matters.
- Villarreal lost at trial and appealed based on a 6th amendment violation of his right to effective council. The Texas Court of Appeals (1st appeal) affirmed the restriction over a dissent and the Court of Criminal Appeals (2nd appeal) did the same.
- The restriction falls between precedent set in Perry v. Leeke (allowing a 15 minute no-confferal order) and Geders v. US (finding that an overnight no-confferal order violates the 6th amendment).
- I don't know what to make of the court's interest in not allowing a defendant to discuss his testimony during a recess. The dissents note that the restriction in place was quite broad; not being able to discuss the defendants testimony about his alleged murder doesn't leave much of substance in a murder trial. This is quite a clean case but the area between Geders and Perry is small.
** OA
- sounding like a 9-0 upholding the restriction.
- There is space between Texas' position and the SG who would allow even more expansive restrictions.

* Berk v. Choy // https://www.scotusblog.com/cases/case-files/berk-v-choy/
- Berk broke his leg and sought care under Dr. Choy in Delaware. Berk sued Choy and his hospital for malpractice in federal court. Delaware law requires a signed affidavit of merit by an expert witness. Under the Erie doctrine, “a federal court sitting in diversity must apply substantive state law and federal procedural law.”
- Defendants claim that the court must apply the affidavit requirement because it is a substantive state law. Berk claims that this requirement conflicts with the FRCP and so cannot apply. Berk argues that rules 8 and 9 lay out the general and special rules for pleading and the Delaware law creates a contrary, more demanding requirement.
- The 3rd circuit, upholding the dismissal in favor of Choy, found that the Delaware law required a separately filed affidavit, which is not a pleading, and so is not contradicted by the rules on pleadings.
- I think there are some logic problems to reading the FCRP as providing a maxmimum barrier to pleading. If states can't make it harder to plead a case could states make it easier to plead? If they can't do either then what "substantive state law" could possibly be applied?
** OA
- Plaintiff is setting up a very narrow ruling where this law is part of a comprehensive procedure for these cases. It wouldn't make sense to pick out one part and include it in the federal rules.

* Barrett v. US // https://www.scotusblog.com/2025/10/justices-to-apply-double-jeopardy-principles-to-federal-firearm-offense/
- Barrett committed several armed robberies. During one, one of his coconspirators shot and killed a victim. in 2013 Barrett was convicted of a number of crimes including using a firearm to advance a violent or drug trafficking crime.
- Barrett argued that he cannot be punished for both the 924(c) firearms charge and the 924(j) murder with a firearm charge. Such a sentence violates the double jeopardy clause of the 5th amendment.
- In Blockburger v. US the supreme court found that two statutory violations can be two offenses when each "requires proof of a fact which the other does not." However Blockburger can be overcome with clear legislative intent.
- 924(c)(1)(D)(ii) "no term of imprisonment imposed on a person under this subsection shall run concurrently with any other term of imprisonment imposed on the person [...]"
- Is that clear enough?
** OA
- Lenity mentioned!
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-5774new_f20h.pdf
- Jackson finds that the presumption from Blockburger holds. "Congress did not clearly manifest a contrary intention [...] to authorize two convictions in these circumstance". So what does that text about concurrent imprisonment mean? Jackson says it's the predicate offense of the 924(c) charge. 924(c) punishes someone for having gun while committing a crime of violence or drug trafficking. The sentence for 924(c) cannot be concurrent to sentence of the crime of violence or drug trafficking. While 924(c) enforces stacking minimum sentences, 924(j) opens the maximum up to a life sentence or the death penalty. Jackson then walks through the two steps of Blockburger: (1) does each offense require proof of fact that the other dose not? If you have committed an offense under 924(j) you have committed an offense under 924(c), so yes; (2) did Congress clearly intended to authorize multiple convictions for one act? no, statutory language describing multiple sentences does not clearly state an intent to authorize multiple convictions.
- Gorsuch's concurence accuses the law of being inconsistant about the meaning of double-jeopardy. If a person is convicted for committing a crime they cannot later be prosecuted and convicted for another crime arising from the same actions. However if prosecutors bring multiple charges that carry non-concurent sentences then double-jeopardy need only be overcome by clear Congressional intent. 

* Chiles v. Salazar // https://www.scotusblog.com/cases/case-files/chiles-v-salazar/
- Chiles is a liscenced therapist in Colorado. Chiles works with clients to "reduce or eliminate unwanted sexual attractions"--conversion therapy. In 2019 Colorado passed a law prohibiting mental helath professionals from practicing conversion therapy. Chiles challenged that law as a violation of her 1st amendment right to speak.
- The district court denied an injunction of the law and the 10th circuit upheld the decision. They found that the law regulated the conduct of a mental health professional which only "incidentally involves speech".
- The court found that because of the statute regulates professional conduct, is viewpoint neutral and does not impose content-based speech restrictions (yes it does?) it is subject to rational basis review, and survives.
- A therapist can help a client accept their sexual attractions. A therapist can not help a client "reduce or eliminate" their sexual attractions. This seems pretty content based to me.
- Chiles argues that because her sole conduct is speech any restriction is a restriction on "pure speech" and therefore subject to strict scrutiny.
- Probably enough here to have some heightened scrutiny. I expect scotus will say it's not rational basis--try again.
** OA
- Chiles wants very narrow rule that applies only to therapy that is entirely speech.

* Bost v. Illinois State Board of Elections // https://www.scotusblog.com/2025/10/when-may-a-candidate-challenge-election-rules-in-federal-court/
- Michael Bost (Ill. 12th) wants to challenge Illinois election law which states that votes by mail are counted if received up to 14 days after election day and postmarked by election day.
- The district court found that Bost lacked standing. There is no particularized harm or cost to him.
- Bost argues that he is injured as the longer time to count votes requires him to employ poll watchers and other observers. Bost also argues that a candidate for office should have standing to challenge the rules that govern their elections--that by running in the election they have a distinct, particularized and concrete interest in the election's rules. Also standing is too complicated and this would be a lot easier.
- Scotus isn't gonna go for the blanket rule. They will likely find that expenses related to a continued campaign gives him standing to challenge rules that extend the election.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-568new_4gcj.pdf
- Roberts writing for the majority finds that "a candidate has a personal stake in the rules that govern the counting of votes in his election". The candidate does not need to show that the rules will effect the outcome. The candidate does not need to show that the rule will cost them money. The candidate doesn't even need to have a marginal change, because "the long-shot and shooin alike would suffer harm". Roberts includes a dubious metaphor to a foot race where racers would have an interest in changes to the distance.
- The candidate has standing because they seek to represent the people and their interest in the process cannot be severed from their interest in that prize. The candidate also suffers reputational harm if the public believes the candidate receieved an unfair advantage. These interests do not extend to the voting public and so this does not create standing for anyone to challenge election rules.
- Roberts also wants to avoid any difficult analysis of expected outcomes or delayed litigation that could implicate purcell.
- Barrett (joined by Kagan) argue that Bost has standing from the costs of extended counting. Bost will "reasonably incur costs to mitigate or avoid" harm caused by allowing late arriving ballots.
- Jackson (Joined by Sotomayor) agrees with the concurance that the bespoke candidate rule is wrong, but also find Bost's pocketbook arguments insufficient. Jackson argues that this rule change does not require the candidate to spend additional resources and so extending ballot watching 14 days is a self inflicted injury that cannot support standing.

* US Postal Service v. Konan // https://www.scotusblog.com/cases/case-files/united-states-postal-service-v-konan/
- Konan maintained rental properties which received mail from USPS. based on her complaint USPS: changed the locks on her multi-family mailbox, refused to deliver mail there, refused to facilitate picking up her mail from the post office, and caused her to lose tenannts and caused the loss of important mail for two years.
- You can't sue the government because of sovereign immunity. The federal tort claims act (FTCA) waives sovereign immunity for "negligent or wrongful acts or omissions of ther government and its employees in limited circumstances." The FTCA explicitly retains sovereign immunity for "[a]ny claim arising out of the loss, miscarriage, or negligent transmission or letters or postal matter." (postal-matter exception)
- The district court held that this was loss so USPS is immune. The 5th circuit disagreed: "there was no “loss” of mail because the mail was not destroyed or misplaced by unintentional action".
- I guess the postal-matter exception specified negligent for "transmission" so you might assume the other things aren't negligent... but... you cannot sue USPS for loss of mail. Sorry!

* Bowe v. US // https://www.scotusblog.com/cases/case-files/bowe-v-united-states/
- Bowe and three friends robbed an armored van servicing a bank. They didn't get any money but Bowe did shoot the driver. Bowe was sentenced to 24 years in prison for conspiracy to commit Hobbs Act robbery, Attempted Hobbs Act robbery, and using a firearm in furtherance of a crime of violence 18 924(c).
- Bowe is challenging the 924(c) charge because his wasn't a "crime of violence". Okay... he did some violence, but robbery isn't a "crime of violence". Look! SCOTUS said so right here (https://www.scotusblog.com/cases/case-files/united-states-v-taylor/)
- But Bowe had already challenged his 924(c) charge before US v. Taylor. In order to bring a "second or successive" habeas petition unless "the claim relies on a new rule of constitutional law". US v. Taylor a decision based on statutory interpretation.
- Also apparently a rule that only applies to state inmates was applied by the 11th circuit... oops. Now we get a court appointed advocate to get knocked around on that one.
- Hobbs Act robbery may not be a "crime of violence" but his crime was violent. That seems like it should matter! SCOTUS could also not get there by saying that he doesn't get another Habeas petition. I'm thinking the bad man stays in jail.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-5438_o7kq.pdf
- Sotomayor initially holds that this second or successive application authorization rulings can be appealed to SCOTUS. When an inmate brings a second or successive appeal they must seek authorization from a circuit panel. 2244(b)(3)(E) says that rulings on those appeals "shall not be the subject or a petition [...] for a writ of certiorari". But 2244 applies to state prisoners. 2255(h) describes the process for second or successive motion certifications for federal prisoners. 2255(h) is less strict. 2255(h) "A second or successive motion must be certified as provided in section 2244 by a panel of the appropriate court of appeals [...]". This does not apply all the same rules from 2244 to 2255, but uses the procedure to apply 2255(h) content requirements.
- Sotomayor then finds that the 2244(b)(1) bar on second or successive applications doesn't apply to federal inmates. This overturns the 11th circuit rule.
- Gorsuch argues that 2255(h)'s reference to 2244 means "the same rules apply to federal prisoners". If that's the case then Bowe fails on jurisdiction and SCOTUS can't reach the merits.
- Gorsuch accuses the majority of wanting to get to the merits to resolve a circuit split. This case would have to be brought by certified question, not certiorari, which sidesteps the stripped jurisdiction. (I guess because 2244 doesn't say you can't appeal it just says can't petition for certiorari? I don't understand what this does functionally.)
* Ellingburg v. US // https://www.scotusblog.com/2025/10/court-to-consider-the-nature-of-restitution/
- US Const. a1s9c3 "No [...] ex post facto Law shall be passed." This means congress can't pass a law after someone did something wrong and use the new law to punish them. They have to pass the law beforehand. This only applies to criminal laws.
- Ellingburg was convicted of robbing a bank and under the 1996 Mandator Victims Restitution Act he was required to pay some restitution.
- Ellingburg argues that this is a criminal punishment and so unconstitutional under the ex post facto clause. It is imposed as part of the criminal sentence, the amount is set by the trial judge, at the end of trial, as part of the sentence. The statute uses criminal procedures. The victims (who get the restitution) have little role and cannot initiate a proceeding. The punishment for failing to pay the restitution is incarceration.
- The court appointed an amicous to argue in favor of the ruling below.

* Case v. Montana // https://www.scotusblog.com/2025/10/justices-to-consider-circumstances-in-which-police-may-enter-a-home-during-an-emergency/
- Case called his girlfriend while drinking and threatening suicide. Case had a handgun and threatened harm to responding officers. His girlfriend told the police and met the police outside Case's house. Officers did not consider obtaining a warrant. Officers called their chief for help who arrived 30 minutes after them. Case did not respond to knocks on the doors or calls from outside. The officers walked in the unlocked front door, announcing themselves. When the first officer saw Case they saw a "dark object" and shot him in the abdomen.
- Case is being charged with Assault on a Peace Officer. Case is moving to suppress evidence obtained in the search of his home. SCOTUS found in Brigham City v. Stuart that no warrant is required to enter a home if police "have an objectively reasonable basis for believing that an occupant is seriously injured or imminently threatened with such injury". The trial court ruled that the officers met that burden, the Montana Supreme Court upheld that decision.
- Case argues this "objectively reasonable basis" should be equivilant to probable cause.
- 4th amendment says "unreasonable" and "reasonable suspicision" does have the word "reasonable" in it. But that's very dumb. The standard to for searching someone's house is probable cause.
** opinion // https://www.supremecourt.gov/opinions/25pdf/24-624_b07d.pdf
- Kagan holds that Objectively reasonable is neither reasonable basis nor probable cause. A police officer can enter a home without a warrant if he has an objectively reasonable basis that someone is in need of emergency aid. An objectively reasonable basis requires specific and articulable facts leading an officer to suspect someone needs help under Brigham City. This is different from reasonable suspicion required for detainment under Terry. An emergency-aid entry does not allow officers to search the premises beyond what is reasonably needed to deal with the emergency.
- Gorsuch's concurance mentions that this is not a special priviledge of law enforcement, "officers generally enjoy the same legal privileges as private citizens". He also argues that this 4th amendment exception comes from common law.

* Louisiana v. Callais // https://www.scotusblog.com/cases/case-files/louisiana-v-callais-2/
- In 2022 Louisiana redrew their congressional districts. That map was challenged by black voters as violating the VRA. The court agreed and ordered Louisiana to draw a map with another majority-black district. In 2024 Louisiana drew a new map with two majority-black districts. This map is being challenged by non-African American voters as violating the equal protection clause. The court agreed and ordered the state not to use that map in 2024 until SCOTUS stayed that decision pending appeal.
- It's the same case as last term, but again! with feeling!
